// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the abstract interface for a Market Data source.

#pragma once
#include <TMQCore/dll.h>

#include <TMQCore/mktdata_entities.h>

#include <vector>
#include <optional>

namespace TMQ
{

class MktDataSource
{
public:
	virtual ~MktDataSource() = default;

    // --- Methods for FXRate (FXR) ---
    [[nodiscard]] TMQCore_API virtual std::vector<MDEntities::FXRate> fetchFXRates( const std::string_view mktName ) = 0;
    [[nodiscard]] TMQCore_API virtual std::optional<MDEntities::FXRate> fetchFXRate( const std::string_view mktName, const std::string_view ID ) = 0;
    TMQCore_API virtual void insertFXRates( const std::vector<MDEntities::FXRate>& data, const std::string_view mktName ) = 0;

    // --- Methods for EQPrice (EQP) ---
    [[nodiscard]] TMQCore_API virtual std::vector<MDEntities::EQPrice> fetchEQPrices( const std::string_view mktName ) = 0;
    [[nodiscard]] TMQCore_API virtual std::optional<MDEntities::EQPrice> fetchEQPrice( const std::string_view mktName, const std::string_view ID ) = 0;
    TMQCore_API virtual void insertEQPrices( const std::vector<MDEntities::EQPrice>& data, const std::string_view mktName ) = 0;

};

}