// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains the RefDataManager class and its cache for Reference Data entities.

#pragma once
#include <TMQCore/dll.h>

#include <TMQUtils/hashers.h>
#include <TMQCore/refdata_entities.h>
#include <TMQCore/logger.h>
#include <TMQCore/refdata_source.h>

#include <map>
#include <functional>
#include <optional>

namespace TMQ
{

class RefDataManager;

template<RDEntities::c_RDEntity T>
class RefDataCache
{
public:
    using KeyType = typename RDEntities::Traits<T>::KeyType;

public:
    explicit RefDataCache( const std::map<KeyType, T>&& map )
        : m_map( std::move( map ) )
    {}

    [[nodiscard]] std::optional<std::reference_wrapper<const T>> get( const KeyType& id ) const
    {
        const auto it = m_map.find( id );
        if( it == m_map.end() )
            return std::nullopt;

        return std::cref( it->second );
    }

private:
    std::map<KeyType, T> m_map;

    friend class RefDataManager;
};

class RefDataManager
{
public:

    enum StaleCheck
    {
        NONE = 0,
        USING_CACHE,
        USING_DB
    };

public:
    RefDataManager( const std::shared_ptr<RefDataSource>& source = nullptr )
	    : m_rdSource( source ? source : GlobalRefDataSource::get() )
    {}

    // --- Methods for Currency (CCY) ---

    [[nodiscard]] TMQCore_API bool hasCurrencies() const;

    [[nodiscard]] TMQCore_API std::shared_ptr<RefDataCache<RDEntities::Currency>> Currencies() const;

    TMQCore_API void reloadCurrencies();

    TMQCore_API void insertCurrencies( const std::vector<RDEntities::Currency>& data, const StaleCheck staleCheck = USING_CACHE );
    TMQCore_API void insertCurrency( const RDEntities::Currency& data, const StaleCheck staleCheck = USING_CACHE );

    // --- Methods for User (USER) ---

    [[nodiscard]] TMQCore_API bool hasUsers() const;

    [[nodiscard]] TMQCore_API std::shared_ptr<RefDataCache<RDEntities::User>> Users() const;

    TMQCore_API void reloadUsers();

    TMQCore_API void insertUsers( const std::vector<RDEntities::User>& data, const StaleCheck staleCheck = USING_CACHE );
    TMQCore_API void insertUser( const RDEntities::User& data, const StaleCheck staleCheck = USING_CACHE );

private:
    // --- Methods for Currency (CCY) ---
    void loadInitiallyCurrencies();

    // --- Methods for User (USER) ---
    void loadInitiallyUsers();

private:
    std::shared_ptr<RefDataSource> m_rdSource;
    mutable std::shared_mutex m_mut;

    std::shared_ptr<RefDataCache<RDEntities::Currency>> m_Currencies;
    std::shared_ptr<RefDataCache<RDEntities::User>> m_Users;
};

}