// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains functions for querying mktdata from ClickHouse.

#include "ch_mktdata_queries.h"

#include <ARQUtils/error.h>
#include <ARQUtils/instr.h>
#include <ARQUtils/logger.h>

#include <clickhouse/client.h>

using namespace ARQ::MD;

namespace ARQ::CH::MD
{

// --- Implementation for FXRate ---

template<>
std::vector<Record<FXRate>> select( CHConn& conn, const std::string_view mktName, const std::vector<std::string_view>& ids )
{
    std::vector<Record<FXRate>> results;
    
    Instr::Timer tm;

    static constexpr auto SELECT_STMT = R"(
		SELECT
            ID,
            argMax(Mid, (AsofTs, _LastUpdatedTs)) AS max_Mid,
            argMax(Bid, (AsofTs, _LastUpdatedTs)) AS max_Bid,
            argMax(Ask, (AsofTs, _LastUpdatedTs)) AS max_Ask,
            argMax(AsofTs, (AsofTs, _LastUpdatedTs)) AS max_AsofTs,
            argMax(_IsActive, (AsofTs, _LastUpdatedTs)) AS max_IsActive,
            argMax(_LastUpdatedTs, (AsofTs, _LastUpdatedTs)) AS max_LastUpdatedTs,
            argMax(_LastUpdatedBy, (AsofTs, _LastUpdatedTs)) AS max_LastUpdatedBy
		FROM MktData.FXRates
        WHERE MarketName = '{0}' {1}
        GROUP BY ID
		HAVING max_IsActive = 1;
	)";

    std::string whereClause;
    if( ids.size() )    
        whereClause = std::format( "AND ID IN ({})", Str::joinFmt( ids, "'{}'", ", " ) );
    
    try
    {
        conn.client().Select( std::format( SELECT_STMT, mktName, whereClause ), [&] ( const clickhouse::Block& block )
        {
            if( block.GetRowCount() == 0 )
                return; // End of data

			auto col_id = block[0]->As<clickhouse::ColumnString>();
            auto col_mid = block[1]->As<clickhouse::ColumnFloat64>();
            auto col_bid = block[2]->As<clickhouse::ColumnFloat64>();
            auto col_ask = block[3]->As<clickhouse::ColumnFloat64>();
            auto col_asofTs = block[4]->As<clickhouse::ColumnDateTime64>();
            auto col_isActive = block[5]->As<clickhouse::ColumnUInt8>();
            auto col_lastUpdatedTs = block[6]->As<clickhouse::ColumnDateTime64>();
            auto col_lastUpdatedBy = block[7]->As<clickhouse::ColumnString>();

            results.reserve( results.size() + block.GetRowCount() );
            for( size_t i = 0; i < block.GetRowCount(); ++i )
            {
                ARQ::MD::Record<ARQ::MD::FXRate> obj;
				obj.header.id = col_id->At( i );
                obj.data.mid = col_mid->At( i );
                obj.data.bid = col_bid->At( i );
                obj.data.ask = col_ask->At( i );
                obj.header.asofTs = Time::DateTime( Time::Microseconds( col_asofTs->At( i ) ) );
                obj.header.isActive = col_isActive->At( i );
                obj.header.lastUpdatedTs = Time::DateTime( Time::Microseconds( col_lastUpdatedTs->At( i ) ) );
                obj.header.lastUpdatedBy = col_lastUpdatedBy->At( i );
                results.push_back( std::move( obj ) );
            }
        } );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse SELECT query: {}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse SELECT query in {}", tm.duration() );

    return results;
}

template<>
void insert( CHConn& conn, const std::string_view mktName, const std::vector<Record<FXRate>>& data )
{
    Instr::Timer tm;

    try
    {
        auto col_mktName = std::make_shared<clickhouse::ColumnString>();
		auto col_id = std::make_shared<clickhouse::ColumnString>();
        auto col_mid = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_bid = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_ask = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_asofTs = std::make_shared<clickhouse::ColumnDateTime64>( 6 );
        auto col_isActive = std::make_shared<clickhouse::ColumnUInt8>();
		auto col_lastUpdatedTs = std::make_shared<clickhouse::ColumnDateTime64>( 6 );
        auto col_lastUpdatedBy = std::make_shared<clickhouse::ColumnString>();

        col_mktName->Reserve( data.size() );
        col_id->Reserve( data.size() );
        col_mid->Reserve( data.size() );
        col_bid->Reserve( data.size() );
        col_ask->Reserve( data.size() );
        col_asofTs->Reserve( data.size() );
		col_isActive->Reserve( data.size() );
		col_lastUpdatedTs->Reserve( data.size() );
		col_lastUpdatedBy->Reserve( data.size() );

        for( const auto& obj : data )
        {
			col_mktName->Append( mktName );
            col_id->Append( obj.header.id );
            col_mid->Append( obj.data.mid );
            col_bid->Append( obj.data.bid );
            col_ask->Append( obj.data.ask );
            col_asofTs->Append( obj.header.asofTs.microsecondsSinceEpoch() );
            col_isActive->Append( obj.header.isActive );
			col_lastUpdatedTs->Append( obj.header.lastUpdatedTs.microsecondsSinceEpoch() );
            col_lastUpdatedBy->Append( obj.header.lastUpdatedBy );
        }

        clickhouse::Block block;
		block.AppendColumn( "MktName", col_mktName );
        block.AppendColumn( "ID", col_id );
        block.AppendColumn( "Mid", col_mid );
        block.AppendColumn( "Bid", col_bid );
        block.AppendColumn( "Ask", col_ask );
        block.AppendColumn( "AsofTs", col_asofTs );
        block.AppendColumn( "_IsActive", col_isActive );
        block.AppendColumn( "_LastUpdatedBy", col_lastUpdatedBy );
		block.AppendColumn( "_LastUpdatedTs", col_lastUpdatedTs );

        conn.client().Insert( "MktData.FXRates", block );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse INSERT query: {0}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse INSERT query in {}", tm.duration() );
}

// --- Implementation for EQPrice ---

template<>
std::vector<Record<EQPrice>> select( CHConn& conn, const std::string_view mktName, const std::vector<std::string_view>& ids )
{
    std::vector<Record<EQPrice>> results;
    
    Instr::Timer tm;

    static constexpr auto SELECT_STMT = R"(
		SELECT
            ID,
            argMax(Last, (AsofTs, _LastUpdatedTs)) AS max_Last,
            argMax(Bid, (AsofTs, _LastUpdatedTs)) AS max_Bid,
            argMax(Ask, (AsofTs, _LastUpdatedTs)) AS max_Ask,
            argMax(Open, (AsofTs, _LastUpdatedTs)) AS max_Open,
            argMax(Close, (AsofTs, _LastUpdatedTs)) AS max_Close,
            argMax(Volume, (AsofTs, _LastUpdatedTs)) AS max_Volume,
            argMax(AsofTs, (AsofTs, _LastUpdatedTs)) AS max_AsofTs,
            argMax(_IsActive, (AsofTs, _LastUpdatedTs)) AS max_IsActive,
            argMax(_LastUpdatedTs, (AsofTs, _LastUpdatedTs)) AS max_LastUpdatedTs,
            argMax(_LastUpdatedBy, (AsofTs, _LastUpdatedTs)) AS max_LastUpdatedBy
		FROM MktData.EQPrices
        WHERE MarketName = '{0}' {1}
        GROUP BY ID
		HAVING max_IsActive = 1;
	)";

    std::string whereClause;
    if( ids.size() )    
        whereClause = std::format( "AND ID IN ({})", Str::joinFmt( ids, "'{}'", ", " ) );
    
    try
    {
        conn.client().Select( std::format( SELECT_STMT, mktName, whereClause ), [&] ( const clickhouse::Block& block )
        {
            if( block.GetRowCount() == 0 )
                return; // End of data

			auto col_id = block[0]->As<clickhouse::ColumnString>();
            auto col_last = block[1]->As<clickhouse::ColumnFloat64>();
            auto col_bid = block[2]->As<clickhouse::ColumnFloat64>();
            auto col_ask = block[3]->As<clickhouse::ColumnFloat64>();
            auto col_open = block[4]->As<clickhouse::ColumnFloat64>();
            auto col_close = block[5]->As<clickhouse::ColumnFloat64>();
            auto col_volume = block[6]->As<clickhouse::ColumnInt64>();
            auto col_asofTs = block[7]->As<clickhouse::ColumnDateTime64>();
            auto col_isActive = block[8]->As<clickhouse::ColumnUInt8>();
            auto col_lastUpdatedTs = block[9]->As<clickhouse::ColumnDateTime64>();
            auto col_lastUpdatedBy = block[10]->As<clickhouse::ColumnString>();

            results.reserve( results.size() + block.GetRowCount() );
            for( size_t i = 0; i < block.GetRowCount(); ++i )
            {
                ARQ::MD::Record<ARQ::MD::EQPrice> obj;
				obj.header.id = col_id->At( i );
                obj.data.last = col_last->At( i );
                obj.data.bid = col_bid->At( i );
                obj.data.ask = col_ask->At( i );
                obj.data.open = col_open->At( i );
                obj.data.close = col_close->At( i );
                obj.data.volume = col_volume->At( i );
                obj.header.asofTs = Time::DateTime( Time::Microseconds( col_asofTs->At( i ) ) );
                obj.header.isActive = col_isActive->At( i );
                obj.header.lastUpdatedTs = Time::DateTime( Time::Microseconds( col_lastUpdatedTs->At( i ) ) );
                obj.header.lastUpdatedBy = col_lastUpdatedBy->At( i );
                results.push_back( std::move( obj ) );
            }
        } );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse SELECT query: {}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse SELECT query in {}", tm.duration() );

    return results;
}

template<>
void insert( CHConn& conn, const std::string_view mktName, const std::vector<Record<EQPrice>>& data )
{
    Instr::Timer tm;

    try
    {
        auto col_mktName = std::make_shared<clickhouse::ColumnString>();
		auto col_id = std::make_shared<clickhouse::ColumnString>();
        auto col_last = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_bid = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_ask = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_open = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_close = std::make_shared<clickhouse::ColumnFloat64>();
        auto col_volume = std::make_shared<clickhouse::ColumnInt64>();
        auto col_asofTs = std::make_shared<clickhouse::ColumnDateTime64>( 6 );
        auto col_isActive = std::make_shared<clickhouse::ColumnUInt8>();
		auto col_lastUpdatedTs = std::make_shared<clickhouse::ColumnDateTime64>( 6 );
        auto col_lastUpdatedBy = std::make_shared<clickhouse::ColumnString>();

        col_mktName->Reserve( data.size() );
        col_id->Reserve( data.size() );
        col_last->Reserve( data.size() );
        col_bid->Reserve( data.size() );
        col_ask->Reserve( data.size() );
        col_open->Reserve( data.size() );
        col_close->Reserve( data.size() );
        col_volume->Reserve( data.size() );
        col_asofTs->Reserve( data.size() );
		col_isActive->Reserve( data.size() );
		col_lastUpdatedTs->Reserve( data.size() );
		col_lastUpdatedBy->Reserve( data.size() );

        for( const auto& obj : data )
        {
			col_mktName->Append( mktName );
            col_id->Append( obj.header.id );
            col_last->Append( obj.data.last );
            col_bid->Append( obj.data.bid );
            col_ask->Append( obj.data.ask );
            col_open->Append( obj.data.open );
            col_close->Append( obj.data.close );
            col_volume->Append( obj.data.volume );
            col_asofTs->Append( obj.header.asofTs.microsecondsSinceEpoch() );
            col_isActive->Append( obj.header.isActive );
			col_lastUpdatedTs->Append( obj.header.lastUpdatedTs.microsecondsSinceEpoch() );
            col_lastUpdatedBy->Append( obj.header.lastUpdatedBy );
        }

        clickhouse::Block block;
		block.AppendColumn( "MktName", col_mktName );
        block.AppendColumn( "ID", col_id );
        block.AppendColumn( "Last", col_last );
        block.AppendColumn( "Bid", col_bid );
        block.AppendColumn( "Ask", col_ask );
        block.AppendColumn( "Open", col_open );
        block.AppendColumn( "Close", col_close );
        block.AppendColumn( "Volume", col_volume );
        block.AppendColumn( "AsofTs", col_asofTs );
        block.AppendColumn( "_IsActive", col_isActive );
        block.AppendColumn( "_LastUpdatedBy", col_lastUpdatedBy );
		block.AppendColumn( "_LastUpdatedTs", col_lastUpdatedTs );

        conn.client().Insert( "MktData.EQPrices", block );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse INSERT query: {0}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse INSERT query in {}", tm.duration() );
}

}