// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains the implementation of the RefData ClickHouse EntitySource classes.

#include <ARQClickHouse/ch_refdata_source.h>

#include <ARQUtils/error.h>
#include <ARQUtils/instr.h>
#include <ARQUtils/logger.h>

#include "connection.h"

#include <clickhouse/client.h>

namespace ARQ::CH::RD
{

void registerEntitySources( ARQ::RD::Source& source )
{
	source.registerEntitySource<ARQ::RD::Currency>( std::make_unique<CHEntitySource_Currency>() );
	source.registerEntitySource<ARQ::RD::User>( std::make_unique<CHEntitySource_User>() );
}

static clickhouse::UUID toClickHouseUUID( const ID::UUID& arqUUID )
{
    clickhouse::UUID clickHouseUUID;
    std::memcpy( &clickHouseUUID.first, arqUUID.bytes.data(), 8 );
    std::memcpy( &clickHouseUUID.second, arqUUID.bytes.data() + 8, 8 );
    return clickHouseUUID;
}

static ID::UUID toArqUUID( const clickhouse::UUID& clickHouseUUID )
{
    ARQ::ID::UUID arqUUID;
    std::memcpy( arqUUID.bytes.data(), &clickHouseUUID.first, 8 );
    std::memcpy( arqUUID.bytes.data() + 8, &clickHouseUUID.second, 8 );
    return arqUUID;
}

// --- Implementation for Currency ---

std::vector<ARQ::RD::Record<ARQ::RD::Currency>> CHEntitySource_Currency::fetch() const
{
    CHConn conn( dsh() );

    std::vector<ARQ::RD::Record<ARQ::RD::Currency>> results;

    Instr::Timer tm;

    static constexpr auto SELECT_STMT = R"(
		SELECT
            UUID,
            argMax(CcyID, _LastUpdatedTs) AS max_CcyID,
            argMax(Name, _LastUpdatedTs) AS max_Name,
            argMax(DecimalPlaces, _LastUpdatedTs) AS max_DecimalPlaces,
            argMax(SettlementDays, _LastUpdatedTs) AS max_SettlementDays,
            argMax(_IsActive, _LastUpdatedTs) AS max_IsActive,
            max(_LastUpdatedTs) AS max_LastUpdatedTs,
            argMax(_LastUpdatedBy, _LastUpdatedTs) AS max_LastUpdatedBy,
            argMax(_Version, _LastUpdatedTs) AS max_Version
		FROM RefData.Currencies
        GROUP BY UUID
		HAVING max_IsActive = 1;
	)";

    try
    {
        conn.client().Select( SELECT_STMT, [&] ( const clickhouse::Block& block )
        {
            if( block.GetRowCount() == 0 )
                return; // End of data

			auto col_uuid = block[0]->As<clickhouse::ColumnUUID>();
            auto col_ccyID = block[1]->As<clickhouse::ColumnString>();
            auto col_name = block[2]->As<clickhouse::ColumnString>();
            auto col_decimalPlaces = block[3]->As<clickhouse::ColumnUInt8>();
            auto col_settlementDays = block[4]->As<clickhouse::ColumnUInt8>();
            auto col_isActive = block[5]->As<clickhouse::ColumnUInt8>();
            auto col_lastUpdatedTs = block[6]->As<clickhouse::ColumnDateTime64>();
            auto col_lastUpdatedBy = block[7]->As<clickhouse::ColumnString>();
            auto col_Version = block[8]->As<clickhouse::ColumnUInt32>();

            results.reserve( results.size() + block.GetRowCount() );
            for( size_t i = 0; i < block.GetRowCount(); ++i )
            {
                ARQ::RD::Record<ARQ::RD::Currency> obj;
				obj.data.uuid = toArqUUID( col_uuid->At( i ) );
				obj.header.uuid =  obj.data.uuid;
                obj.data.ccyID = col_ccyID->At( i );
                obj.data.name = col_name->At( i );
                obj.data.decimalPlaces = col_decimalPlaces->At( i );
                obj.data.settlementDays = col_settlementDays->At( i );
                obj.header.isActive = col_isActive->At( i );
                obj.header.lastUpdatedTs = Time::DateTime( Time::Microseconds( col_lastUpdatedTs->At( i ) ) );
                obj.header.lastUpdatedBy = col_lastUpdatedBy->At( i );
                obj.header.version = col_Version->At( i );
                results.push_back( std::move( obj ) );
            }
        } );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse SELECT query: {}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse select query in {}", tm.duration() );

    return results;
}

void CHEntitySource_Currency::insert( const std::vector<ARQ::RD::Record<ARQ::RD::Currency>>& data )
{
    CHConn conn( dsh() );

    Instr::Timer tm;

    try
    {
		auto col_uuid = std::make_shared<clickhouse::ColumnUUID>();
        auto col_ccyID = std::make_shared<clickhouse::ColumnString>();
        auto col_name = std::make_shared<clickhouse::ColumnString>();
        auto col_decimalPlaces = std::make_shared<clickhouse::ColumnUInt8>();
        auto col_settlementDays = std::make_shared<clickhouse::ColumnUInt8>();
        auto col_isActive = std::make_shared<clickhouse::ColumnUInt8>();
		auto col_lastUpdatedTs = std::make_shared<clickhouse::ColumnDateTime64>( 6 );
        auto col_lastUpdatedBy = std::make_shared<clickhouse::ColumnString>();
        auto col_Version = std::make_shared<clickhouse::ColumnUInt32>();

        col_uuid->Reserve( data.size() );
        col_ccyID->Reserve( data.size() );
        col_name->Reserve( data.size() );
        col_decimalPlaces->Reserve( data.size() );
        col_settlementDays->Reserve( data.size() );
		col_isActive->Reserve( data.size() );
		col_lastUpdatedTs->Reserve( data.size() );
		col_lastUpdatedBy->Reserve( data.size() );
		col_Version->Reserve( data.size() );

        for( const auto& obj : data )
        {
			col_uuid->Append( toClickHouseUUID( obj.header.uuid ) );
            col_ccyID->Append( obj.data.ccyID );
            col_name->Append( obj.data.name );
            col_decimalPlaces->Append( obj.data.decimalPlaces );
            col_settlementDays->Append( obj.data.settlementDays );
            col_isActive->Append( obj.header.isActive );
			col_lastUpdatedTs->Append( obj.header.lastUpdatedTs.microsecondsSinceEpoch() );
            col_lastUpdatedBy->Append( obj.header.lastUpdatedBy );
            col_Version->Append( obj.header.version );
        }

        clickhouse::Block block;
		block.AppendColumn( "UUID", col_uuid );
        block.AppendColumn( "CcyID", col_ccyID );
        block.AppendColumn( "Name", col_name );
        block.AppendColumn( "DecimalPlaces", col_decimalPlaces );
        block.AppendColumn( "SettlementDays", col_settlementDays );
        block.AppendColumn( "_IsActive", col_isActive );
        block.AppendColumn( "_LastUpdatedBy", col_lastUpdatedBy );
		block.AppendColumn( "_LastUpdatedTs", col_lastUpdatedTs );
        block.AppendColumn( "_Version", col_Version );

        conn.client().Insert( "RefData.Currencies", block );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse INSERT query: {0}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse insert query in {}", tm.duration() );
}

// --- Implementation for User ---

std::vector<ARQ::RD::Record<ARQ::RD::User>> CHEntitySource_User::fetch() const
{
    CHConn conn( dsh() );

    std::vector<ARQ::RD::Record<ARQ::RD::User>> results;

    Instr::Timer tm;

    static constexpr auto SELECT_STMT = R"(
		SELECT
            UUID,
            argMax(UserID, _LastUpdatedTs) AS max_UserID,
            argMax(FullName, _LastUpdatedTs) AS max_FullName,
            argMax(Email, _LastUpdatedTs) AS max_Email,
            argMax(TradingDesk, _LastUpdatedTs) AS max_TradingDesk,
            argMax(_IsActive, _LastUpdatedTs) AS max_IsActive,
            max(_LastUpdatedTs) AS max_LastUpdatedTs,
            argMax(_LastUpdatedBy, _LastUpdatedTs) AS max_LastUpdatedBy,
            argMax(_Version, _LastUpdatedTs) AS max_Version
		FROM RefData.Users
        GROUP BY UUID
		HAVING max_IsActive = 1;
	)";

    try
    {
        conn.client().Select( SELECT_STMT, [&] ( const clickhouse::Block& block )
        {
            if( block.GetRowCount() == 0 )
                return; // End of data

			auto col_uuid = block[0]->As<clickhouse::ColumnUUID>();
            auto col_userID = block[1]->As<clickhouse::ColumnString>();
            auto col_fullName = block[2]->As<clickhouse::ColumnString>();
            auto col_email = block[3]->As<clickhouse::ColumnString>();
            auto col_tradingDesk = block[4]->As<clickhouse::ColumnString>();
            auto col_isActive = block[5]->As<clickhouse::ColumnUInt8>();
            auto col_lastUpdatedTs = block[6]->As<clickhouse::ColumnDateTime64>();
            auto col_lastUpdatedBy = block[7]->As<clickhouse::ColumnString>();
            auto col_Version = block[8]->As<clickhouse::ColumnUInt32>();

            results.reserve( results.size() + block.GetRowCount() );
            for( size_t i = 0; i < block.GetRowCount(); ++i )
            {
                ARQ::RD::Record<ARQ::RD::User> obj;
				obj.data.uuid = toArqUUID( col_uuid->At( i ) );
				obj.header.uuid =  obj.data.uuid;
                obj.data.userID = col_userID->At( i );
                obj.data.fullName = col_fullName->At( i );
                obj.data.email = col_email->At( i );
                obj.data.tradingDesk = col_tradingDesk->At( i );
                obj.header.isActive = col_isActive->At( i );
                obj.header.lastUpdatedTs = Time::DateTime( Time::Microseconds( col_lastUpdatedTs->At( i ) ) );
                obj.header.lastUpdatedBy = col_lastUpdatedBy->At( i );
                obj.header.version = col_Version->At( i );
                results.push_back( std::move( obj ) );
            }
        } );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse SELECT query: {}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse select query in {}", tm.duration() );

    return results;
}

void CHEntitySource_User::insert( const std::vector<ARQ::RD::Record<ARQ::RD::User>>& data )
{
    CHConn conn( dsh() );

    Instr::Timer tm;

    try
    {
		auto col_uuid = std::make_shared<clickhouse::ColumnUUID>();
        auto col_userID = std::make_shared<clickhouse::ColumnString>();
        auto col_fullName = std::make_shared<clickhouse::ColumnString>();
        auto col_email = std::make_shared<clickhouse::ColumnString>();
        auto col_tradingDesk = std::make_shared<clickhouse::ColumnString>();
        auto col_isActive = std::make_shared<clickhouse::ColumnUInt8>();
		auto col_lastUpdatedTs = std::make_shared<clickhouse::ColumnDateTime64>( 6 );
        auto col_lastUpdatedBy = std::make_shared<clickhouse::ColumnString>();
        auto col_Version = std::make_shared<clickhouse::ColumnUInt32>();

        col_uuid->Reserve( data.size() );
        col_userID->Reserve( data.size() );
        col_fullName->Reserve( data.size() );
        col_email->Reserve( data.size() );
        col_tradingDesk->Reserve( data.size() );
		col_isActive->Reserve( data.size() );
		col_lastUpdatedTs->Reserve( data.size() );
		col_lastUpdatedBy->Reserve( data.size() );
		col_Version->Reserve( data.size() );

        for( const auto& obj : data )
        {
			col_uuid->Append( toClickHouseUUID( obj.header.uuid ) );
            col_userID->Append( obj.data.userID );
            col_fullName->Append( obj.data.fullName );
            col_email->Append( obj.data.email );
            col_tradingDesk->Append( obj.data.tradingDesk );
            col_isActive->Append( obj.header.isActive );
			col_lastUpdatedTs->Append( obj.header.lastUpdatedTs.microsecondsSinceEpoch() );
            col_lastUpdatedBy->Append( obj.header.lastUpdatedBy );
            col_Version->Append( obj.header.version );
        }

        clickhouse::Block block;
		block.AppendColumn( "UUID", col_uuid );
        block.AppendColumn( "UserID", col_userID );
        block.AppendColumn( "FullName", col_fullName );
        block.AppendColumn( "Email", col_email );
        block.AppendColumn( "TradingDesk", col_tradingDesk );
        block.AppendColumn( "_IsActive", col_isActive );
        block.AppendColumn( "_LastUpdatedBy", col_lastUpdatedBy );
		block.AppendColumn( "_LastUpdatedTs", col_lastUpdatedTs );
        block.AppendColumn( "_Version", col_Version );

        conn.client().Insert( "RefData.Users", block );
    }
    catch( const std::exception& e )
    {
        throw ARQException( std::format( "Error executing ClickHouse INSERT query: {0}", e.what() ) );
    }

    Log( Module::CLICKHOUSE ).debug( "Ran ClickHouse insert query in {}", tm.duration() );
}

}