// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains interfaces for Reference Data entities.

namespace ARQ.RD;

public interface IEntity { }
public interface IRecord { }

public partial class Currency : IEntity {}
public partial class CurrencyRecord : IRecord {}

public partial class User : IEntity {}
public partial class UserRecord : IRecord {}
