// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains function declarations to convert between RDEntity structs and their gRPC representations.

#pragma once

#include <ARQCore/refdata_entities.h>

#include <proto_gen/refdata_protobuf.grpc.pb.h>

namespace ARQ
{
namespace Grpc
{
namespace RefData
{
// TODO: Add tests

// --- Converters for Currency (CCY) ---

void toGrpc( const RDEntities::Currency& arqEntity, Currency* const grpcEntity );
void toGrpc( RDEntities::Currency&& arqEntity, Currency* const grpcEntity );
void toGrpcPayload( const RDEntities::Currency& arqEntity, CurrencyPayload* const grpcEntityPayload );
void toGrpcPayload( RDEntities::Currency&& arqEntity, CurrencyPayload* const grpcEntityPayload );

[[nodiscard]] RDEntities::Currency fromGrpc( const Currency& grpcEntity );
[[nodiscard]] RDEntities::Currency fromGrpc( Currency&& grpcEntity );
[[nodiscard]] RDEntities::Currency fromGrpcPayload( const CurrencyPayload& grpcEntityPayload );
[[nodiscard]] RDEntities::Currency fromGrpcPayload( CurrencyPayload&& grpcEntityPayload );

// --- Converters for User (USER) ---

void toGrpc( const RDEntities::User& arqEntity, User* const grpcEntity );
void toGrpc( RDEntities::User&& arqEntity, User* const grpcEntity );
void toGrpcPayload( const RDEntities::User& arqEntity, UserPayload* const grpcEntityPayload );
void toGrpcPayload( RDEntities::User&& arqEntity, UserPayload* const grpcEntityPayload );

[[nodiscard]] RDEntities::User fromGrpc( const User& grpcEntity );
[[nodiscard]] RDEntities::User fromGrpc( User&& grpcEntity );
[[nodiscard]] RDEntities::User fromGrpcPayload( const UserPayload& grpcEntityPayload );
[[nodiscard]] RDEntities::User fromGrpcPayload( UserPayload&& grpcEntityPayload );

}
}
}