// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the interface for a ClickHouse Market Data source.

#pragma once
#include <TMQClickHouse/dll.h>

#include <TMQCore/mktdata_entities.h>
#include <TMQCore/mktdata_source_interface.h>

namespace TMQ
{

class CHMktDataSource : public MktDataSource
{
public:
	virtual ~CHMktDataSource() = default;

    // --- Methods for FXRate (FXR) ---
    [[nodiscard]] TMQClickHouse_API std::vector<MDEntities::FXRate> fetchFXRates( const std::string_view mktName ) override;
    [[nodiscard]] TMQClickHouse_API std::optional<MDEntities::FXRate> fetchFXRate( const std::string_view mktName, const std::string_view ID ) override;
    TMQClickHouse_API void insertFXRates( const std::vector<MDEntities::FXRate>& data, const std::string_view mktName ) override;

    // --- Methods for EQPrice (EQP) ---
    [[nodiscard]] TMQClickHouse_API std::vector<MDEntities::EQPrice> fetchEQPrices( const std::string_view mktName ) override;
    [[nodiscard]] TMQClickHouse_API std::optional<MDEntities::EQPrice> fetchEQPrice( const std::string_view mktName, const std::string_view ID ) override;
    TMQClickHouse_API void insertEQPrices( const std::vector<MDEntities::EQPrice>& data, const std::string_view mktName ) override;

};

}