// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the abstract interface for a ClickHouse Reference Data source.

#pragma once
#include <TMQClickHouse/dll.h>

#include <TMQCore/refdata_entities.h>
#include <TMQCore/refdata_source_interface.h>

namespace TMQ
{

class CHRefDataSource : public RefDataSource
{
public:
	virtual ~CHRefDataSource() = default;

    // --- Methods for Currency (CCY) ---
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::Currency> fetchLatestCurrencies() override;
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::Currency> fetchAsOfCurrencies( std::chrono::system_clock::time_point asof ) override;
    TMQClickHouse_API void insertCurrencies( const std::vector<RDEntities::Currency>& data ) override;

    // --- Methods for User (USER) ---
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::User> fetchLatestUsers() override;
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::User> fetchAsOfUsers( std::chrono::system_clock::time_point asof ) override;
    TMQClickHouse_API void insertUsers( const std::vector<RDEntities::User>& data ) override;

};

}