// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the interface for a ClickHouse Reference Data source.

#pragma once
#include <TMQClickHouse/dll.h>

#include <TMQUtils/time.h>
#include <TMQCore/refdata_entities.h>
#include <TMQCore/refdata_source_interface.h>

namespace TMQ
{

class CHRefDataSource : public RefDataSource
{
public:
    CHRefDataSource( const std::string_view dsh )
        : m_dsh( dsh )
    {}
	virtual ~CHRefDataSource() = default;

    // --- Methods for Currency (CCY) ---
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::Currency> fetchLatestCurrencies() override;
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::Currency> fetchAsOfCurrencies( const Time::DateTime asof ) override;
    TMQClickHouse_API void insertCurrencies( const std::vector<RDEntities::Currency>& data ) override;

    // --- Methods for User (USER) ---
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::User> fetchLatestUsers() override;
    [[nodiscard]] TMQClickHouse_API std::vector<RDEntities::User> fetchAsOfUsers( const Time::DateTime asof ) override;
    TMQClickHouse_API void insertUsers( const std::vector<RDEntities::User>& data ) override;

private:
    std::string m_dsh;
};

}