// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Market Data topics.

#include <ARQMarket/mktdata_topics.h>

namespace ARQ::MD
{

Type getTypeFromUpdateTopic( const std::string_view topic )
{
    switch( Str::constexprHash( topic ) )
    {
        case Str::constexprHash( "ARQ.MktData.Updates.FXR" ):
            if( topic == "ARQ.MktData.Updates.FXR" ) 
                return Type::FXR;
            break;
        case Str::constexprHash( "ARQ.MktData.Updates.EQP" ):
            if( topic == "ARQ.MktData.Updates.EQP" ) 
                return Type::EQP;
            break;
    }

    throw ARQException( std::format( "Unknown MktData update topic [{}] - cannot map to entity type", topic ) );
}

}