// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Market Data entities.

#include <ARQMarket/mktdata_entities.h>
#include <ARQMarket/mktdata_meta.h>

namespace ARQ::MD
{

ARQ_REG_MD_ENTITY_META( FXRate );
ARQ_REG_MD_ENTITY_META( EQPrice );

}