-- THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
-- Contains table creation scripts for Market Data entities.

CREATE DATABASE MktData;

-- Schema for FXRate
CREATE TABLE IF NOT EXISTS MktData.FXRates
(
    `MarketName` LowCardinality(String) COMMENT 'The name of the market this data belongs to (e.g., LIVE, EOD_20250724).',
    `ID` String COMMENT 'The unique identifier for the market data entity.',
    `AsofTs` Datetime64(6) COMMENT 'The point-in-time when the market data was effective',
    `Mid` Float64 COMMENT 'The mid-market rate.',
    `Bid` Float64 COMMENT 'The price at which a market maker is willing to buy.',
    `Ask` Float64 COMMENT 'The price at which a market maker is willing to sell.',
    `_IsActive` UInt8 COMMENT 'Indicates if the record is still active',
    `_LastUpdatedTs` Datetime64(6) DEFAULT now64(6) COMMENT 'The timestamp of the last update to this record',
    `_LastUpdatedBy` String COMMENT 'The user who last updated the record'
)
ENGINE = MergeTree
ORDER BY (`MarketName`, `ID`, `AsofTs`, `_LastUpdatedTs`)
COMMENT 'Represents a foreign exchange spot rate.';

-- Schema for EQPrice
CREATE TABLE IF NOT EXISTS MktData.EQPrices
(
    `MarketName` LowCardinality(String) COMMENT 'The name of the market this data belongs to (e.g., LIVE, EOD_20250724).',
    `ID` String COMMENT 'The unique identifier for the market data entity.',
    `AsofTs` Datetime64(6) COMMENT 'The point-in-time when the market data was effective',
    `Last` Float64 COMMENT 'The price of the last executed trade.',
    `Bid` Float64 COMMENT 'The highest price a buyer is willing to pay.',
    `Ask` Float64 COMMENT 'The lowest price a seller is willing to accept.',
    `Open` Float64 COMMENT 'The opening price for the current trading session.',
    `Close` Float64 COMMENT 'The closing price from the previous trading session.',
    `Volume` Int64 COMMENT 'The cumulative volume for the current trading session.',
    `Vwap` Nullable(Float64) COMMENT 'The volume-weighted average price for the current trading session, if available.',
    `_IsActive` UInt8 COMMENT 'Indicates if the record is still active',
    `_LastUpdatedTs` Datetime64(6) DEFAULT now64(6) COMMENT 'The timestamp of the last update to this record',
    `_LastUpdatedBy` String COMMENT 'The user who last updated the record'
)
ENGINE = MergeTree
ORDER BY (`MarketName`, `ID`, `AsofTs`, `_LastUpdatedTs`)
COMMENT 'Represents pricing information for an equity.';

