// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Declares functions for Reference Data serialisation.

#pragma once
#include <ARQSerialisation/dll.h>

#include <ARQUtils/buffer.h>
#include <ARQCore/refdata_entities.h>

#include <fbs_generated/refdata_messages.h>

namespace ARQ
{

// --- Methods for Currency (CCY) ---
[[nodiscard]] ARQSerialisation_API RDEntities::Currency deserialiseCurrency( const fbs::CurrencyPayload& payload );
[[nodiscard]] ARQSerialisation_API Buffer serialiseCurrency( const RDEntities::Currency& entity );

// --- Methods for User (USER) ---
[[nodiscard]] ARQSerialisation_API RDEntities::User deserialiseUser( const fbs::UserPayload& payload );
[[nodiscard]] ARQSerialisation_API Buffer serialiseUser( const RDEntities::User& entity );

}