//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ARQ.RD {

public partial class MemberInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MemberInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MemberInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MemberInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MemberInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARQLibPINVOKE.delete_ARQ_RD_MemberInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string name {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_name_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ARQLibPINVOKE.ARQ_RD_MemberInfo_name_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string comment {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_comment_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ARQLibPINVOKE.ARQ_RD_MemberInfo_comment_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ARQ.PhysicalType physicalType {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_physicalType_set(swigCPtr, (int)value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ARQ.PhysicalType ret = (ARQ.PhysicalType)ARQLibPINVOKE.ARQ_RD_MemberInfo_physicalType_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ARQ.RD.IndexType indexType {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_indexType_set(swigCPtr, (int)value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ARQ.RD.IndexType ret = (ARQ.RD.IndexType)ARQLibPINVOKE.ARQ_RD_MemberInfo_indexType_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ARQ.SemanticFormat format {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_format_set(swigCPtr, (int)value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ARQ.SemanticFormat ret = (ARQ.SemanticFormat)ARQLibPINVOKE.ARQ_RD_MemberInfo_format_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool uiReadOnly {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_uiReadOnly_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = ARQLibPINVOKE.ARQ_RD_MemberInfo_uiReadOnly_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool isPrimaryKey {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_isPrimaryKey_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = ARQLibPINVOKE.ARQ_RD_MemberInfo_isPrimaryKey_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool isOptional {
    set {
      ARQLibPINVOKE.ARQ_RD_MemberInfo_isOptional_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = ARQLibPINVOKE.ARQ_RD_MemberInfo_isOptional_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public MemberInfo() : this(ARQLibPINVOKE.new_ARQ_RD_MemberInfo(), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
