//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ARQ.RD {

public partial class UserRecordList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<ARQ.RD.UserRecord>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UserRecordList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UserRecordList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UserRecordList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~UserRecordList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARQLibPINVOKE.delete_ARQ_RD_UserRecordList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UserRecordList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ARQ.RD.UserRecord element in c) {
      this.Add(element);
    }
  }

  public UserRecordList(global::System.Collections.Generic.IEnumerable<ARQ.RD.UserRecord> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ARQ.RD.UserRecord element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ARQ.RD.UserRecord this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ARQ.RD.UserRecord[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ARQ.RD.UserRecord[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ARQ.RD.UserRecord[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public ARQ.RD.UserRecord[] ToArray() {
    ARQ.RD.UserRecord[] array = new ARQ.RD.UserRecord[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<ARQ.RD.UserRecord> global::System.Collections.Generic.IEnumerable<ARQ.RD.UserRecord>.GetEnumerator() {
    return new UserRecordListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new UserRecordListEnumerator(this);
  }

  public UserRecordListEnumerator GetEnumerator() {
    return new UserRecordListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class UserRecordListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ARQ.RD.UserRecord>
  {
    private UserRecordList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public UserRecordListEnumerator(UserRecordList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ARQ.RD.UserRecord Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ARQ.RD.UserRecord)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public UserRecordList() : this(ARQLibPINVOKE.new_ARQ_RD_UserRecordList__SWIG_0(), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public UserRecordList(ARQ.RD.UserRecordList other) : this(ARQLibPINVOKE.new_ARQ_RD_UserRecordList__SWIG_1(ARQ.RD.UserRecordList.getCPtr(other)), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_Clear(swigCPtr);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(ARQ.RD.UserRecord x) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_Add(swigCPtr, ARQ.RD.UserRecord.getCPtr(x));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = ARQLibPINVOKE.ARQ_RD_UserRecordList_size(swigCPtr);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool empty() {
    bool ret = ARQLibPINVOKE.ARQ_RD_UserRecordList_empty(swigCPtr);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = ARQLibPINVOKE.ARQ_RD_UserRecordList_capacity(swigCPtr);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_reserve(swigCPtr, n);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public UserRecordList(int capacity) : this(ARQLibPINVOKE.new_ARQ_RD_UserRecordList__SWIG_2(capacity), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private ARQ.RD.UserRecord getitemcopy(int index) {
    global::System.IntPtr cPtr = ARQLibPINVOKE.ARQ_RD_UserRecordList_getitemcopy(swigCPtr, index);
    ARQ.RD.UserRecord ret = (cPtr == global::System.IntPtr.Zero) ? null : new ARQ.RD.UserRecord(cPtr, false);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ARQ.RD.UserRecord getitem(int index) {
    global::System.IntPtr cPtr = ARQLibPINVOKE.ARQ_RD_UserRecordList_getitem(swigCPtr, index);
    ARQ.RD.UserRecord ret = (cPtr == global::System.IntPtr.Zero) ? null : new ARQ.RD.UserRecord(cPtr, false);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ARQ.RD.UserRecord val) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_setitem(swigCPtr, index, ARQ.RD.UserRecord.getCPtr(val));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(ARQ.RD.UserRecordList values) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_AddRange(swigCPtr, ARQ.RD.UserRecordList.getCPtr(values));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public ARQ.RD.UserRecordList GetRange(int index, int count) {
    global::System.IntPtr cPtr = ARQLibPINVOKE.ARQ_RD_UserRecordList_GetRange(swigCPtr, index, count);
    ARQ.RD.UserRecordList ret = (cPtr == global::System.IntPtr.Zero) ? null : new ARQ.RD.UserRecordList(cPtr, true);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ARQ.RD.UserRecord x) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_Insert(swigCPtr, index, ARQ.RD.UserRecord.getCPtr(x));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, ARQ.RD.UserRecordList values) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_InsertRange(swigCPtr, index, ARQ.RD.UserRecordList.getCPtr(values));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_RemoveAt(swigCPtr, index);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_RemoveRange(swigCPtr, index, count);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ARQ.RD.UserRecordList Repeat(ARQ.RD.UserRecord value, int count) {
    global::System.IntPtr cPtr = ARQLibPINVOKE.ARQ_RD_UserRecordList_Repeat(ARQ.RD.UserRecord.getCPtr(value), count);
    ARQ.RD.UserRecordList ret = (cPtr == global::System.IntPtr.Zero) ? null : new ARQ.RD.UserRecordList(cPtr, true);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_Reverse__SWIG_0(swigCPtr);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_Reverse__SWIG_1(swigCPtr, index, count);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, ARQ.RD.UserRecordList values) {
    ARQLibPINVOKE.ARQ_RD_UserRecordList_SetRange(swigCPtr, index, ARQ.RD.UserRecordList.getCPtr(values));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(ARQ.RD.UserRecord value) {
    bool ret = ARQLibPINVOKE.ARQ_RD_UserRecordList_Contains(swigCPtr, ARQ.RD.UserRecord.getCPtr(value));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int IndexOf(ARQ.RD.UserRecord value) {
    int ret = ARQLibPINVOKE.ARQ_RD_UserRecordList_IndexOf(swigCPtr, ARQ.RD.UserRecord.getCPtr(value));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LastIndexOf(ARQ.RD.UserRecord value) {
    int ret = ARQLibPINVOKE.ARQ_RD_UserRecordList_LastIndexOf(swigCPtr, ARQ.RD.UserRecord.getCPtr(value));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Remove(ARQ.RD.UserRecord value) {
    bool ret = ARQLibPINVOKE.ARQ_RD_UserRecordList_Remove(swigCPtr, ARQ.RD.UserRecord.getCPtr(value));
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
