//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ARQ.RD {

public partial class User : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal User(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(User obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(User obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~User() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARQLibPINVOKE.delete_ARQ_RD_User(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ARQ.ID.UUID uuid {
    set {
      ARQLibPINVOKE.ARQ_RD_User_uuid_set(swigCPtr, ARQ.ID.UUID.getCPtr(value));
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = ARQLibPINVOKE.ARQ_RD_User_uuid_get(swigCPtr);
      ARQ.ID.UUID ret = (cPtr == global::System.IntPtr.Zero) ? null : new ARQ.ID.UUID(cPtr, false);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string userID {
    set {
      ARQLibPINVOKE.ARQ_RD_User_userID_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ARQLibPINVOKE.ARQ_RD_User_userID_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string fullName {
    set {
      ARQLibPINVOKE.ARQ_RD_User_fullName_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ARQLibPINVOKE.ARQ_RD_User_fullName_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string email {
    set {
      ARQLibPINVOKE.ARQ_RD_User_email_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ARQLibPINVOKE.ARQ_RD_User_email_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string tradingDesk {
    set {
      ARQLibPINVOKE.ARQ_RD_User_tradingDesk_set(swigCPtr, value);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ARQLibPINVOKE.ARQ_RD_User_tradingDesk_get(swigCPtr);
      if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public User() : this(ARQLibPINVOKE.new_ARQ_RD_User(), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
