//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace std {

internal class OptSignedShort : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OptSignedShort(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OptSignedShort obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OptSignedShort obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OptSignedShort() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARQLibPINVOKE.delete_std_OptSignedShort(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public OptSignedShort() : this(ARQLibPINVOKE.new_std_OptSignedShort__SWIG_0(), true) {
  }

  public OptSignedShort(short value) : this(ARQLibPINVOKE.new_std_OptSignedShort__SWIG_1(value), true) {
  }

  public OptSignedShort(std.OptSignedShort other) : this(ARQLibPINVOKE.new_std_OptSignedShort__SWIG_2(std.OptSignedShort.getCPtr(other)), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool has_value() {
    bool ret = ARQLibPINVOKE.std_OptSignedShort_has_value(swigCPtr);
    return ret;
  }

  public short value() {
    short ret = ARQLibPINVOKE.std_OptSignedShort_value(swigCPtr);
    return ret;
  }

}

}
