// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains extension methods for Repository to access Reference Data entities.

namespace ARQ.RD;

public static class RepositoryExtensions
{
    public static ICache? getByName(this Repository repo, string entityName)
    {
        return entityName.ToLowerInvariant() switch
        {
            "currency" => repo.getCurrencies(),
            "user" => repo.getUsers(),

            _ => null
        };
    }
}