// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains functions for building refdata cache indexes for each RefData entity.

// IMPORTANT: Do not include this file anywhere!
// It's only designed to be included at the bottom of refdata_repository.h

#pragma once

namespace ARQ::RD
{

template<c_RefData T>
inline void buildCacheIndexes( Cache<T>& cache )
{
    // Default implementation does nothing
}

template<>
inline void buildCacheIndexes( Cache<Currency>& cache )
{
    Cache<Currency>::UniqueIndexMap& ccyIDUniqIndex = cache.m_uniqueIndices.emplace_back( "ccyID", Cache<Currency>::UniqueIndexMap() ).second;
    
    for( const auto& [id, record] : cache.m_map )
    {
        ccyIDUniqIndex.emplace( record.data.ccyID, id );
    }   
}

template<>
inline void buildCacheIndexes( Cache<User>& cache )
{
    Cache<User>::UniqueIndexMap& userIDUniqIndex = cache.m_uniqueIndices.emplace_back( "userID", Cache<User>::UniqueIndexMap() ).second;
    Cache<User>::NonUniqueIndexMap& tradingDeskNonUniqIndex = cache.m_nonUniqueIndices.emplace_back( "tradingDesk", Cache<User>::NonUniqueIndexMap() ).second;
    
    for( const auto& [id, record] : cache.m_map )
    {
        userIDUniqIndex.emplace( record.data.userID, id );
        tradingDeskNonUniqIndex[record.data.tradingDesk.value_or( "" )].push_back( id );
    }   
}

}