// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Reference Data entities.

#pragma once

#include <ARQUtils/error.h>
#include <ARQUtils/types.h>
#include <ARQUtils/time.h>
#include <ARQUtils/id.h>
#include <ARQUtils/str.h>
#include <ARQUtils/tuple_vector.h>
#include <ARQCore/type_registry.h>
#include <ARQCore/semantic_format.h>
#include <ARQCore/physical_type.h>

#include <string>
#include <cstdint>
#include <string_view>
#include <array>
#include <utility>

namespace ARQ::RD
{

#pragma region Common RefData Types

/*
*********************************************
*    Common types for RefData Entities      *
*********************************************
*/

ARQ_DEFINE_TYPE_CATEGORY( RefData );

/// Traits class to get compile-time metadata about an entity
template<c_RefData T>
class Traits {};

enum class IndexType
{
    None,
    Unique,   // 1-to-1
    NonUnique // 1-to-Many
};

/// Records metadata about each member in a RD type
struct MemberInfo
{
    /// Name of the C++ member variable
    std::string_view name;
    /// Documentation string
    std::string_view comment;
    /// The physical type
    PhysicalType     physicalType;
    // Indicates if member is an index, and what type
    IndexType        indexType;
    // Format to use when rendering in the UI
    SemanticFormat   format;
    // Indicates if member is read-only in the UI
    bool             uiReadOnly;
    // Indicates if member is part of the primary key
    bool             isPrimaryKey;
};

/// Metadata header common to all Reference Data records
struct RecordHeader
{
    /// The immutable, globally unique system identifier (Machine Key)
    ID::UUID       uuid;
    /// Indicates if the record is still active - false means it's been 'tombstoned'
    bool           isActive;
    /// The timestamp of the last update to this record
    Time::DateTime lastUpdatedTs;
    /// The user who last updated the record
    std::string    lastUpdatedBy;
    /// Optimistic Concurrency Control (OCC) version number
    uint32_t       version;

    static constexpr std::array<MemberInfo, 5> membersInfo =
    {
        MemberInfo {
            .name         = "uuid",
            .comment      = "The immutable, globally unique system identifier (Machine Key).",
            .physicalType = PhysicalType::UUID,
            .indexType    = IndexType::Unique,
            .format       = SemanticFormat::UUID,
            .uiReadOnly   = true,
            .isPrimaryKey = true
        },
        MemberInfo {
            .name         = "isActive",
            .comment      = "Indicates if the record is still active - false means it's been 'tombstoned'.",
            .physicalType = PhysicalType::Boolean,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::Boolean,
            .uiReadOnly   = true,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "lastUpdatedTs",
            .comment      = "The timestamp of the last update to this record.",
            .physicalType = PhysicalType::DateTime,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::DateTime,
            .uiReadOnly   = true,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "lastUpdatedBy",
            .comment      = "The user who last updated the record.",
            .physicalType = PhysicalType::String,
            .indexType    = IndexType::NonUnique,
            .format       = SemanticFormat::String,
            .uiReadOnly   = true,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "version",
            .comment      = "Optimistic Concurrency Control (OCC) version number.",
            .physicalType = PhysicalType::UInt32,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::Integer,
            .uiReadOnly   = true,
            .isPrimaryKey = false
        }
    };
};

/// The generic storage container for all Reference Data entities
template<c_RefData T>
struct Record
{
    using EntityType = T;

    /// Entity metadata
    RecordHeader header;
    /// The actual entity data
    T            data;
};

#pragma endregion

#pragma region RefData Entities

/*
***********************************
* Definitions of RefData entities *
***********************************
*/

// -------------------- Currency RefData entity --------------------

/// Represents an ISO 4217 currency and its conventions.
struct Currency
{
    /// The immutable, globally unique system identifier (Machine Key)
    ID::UUID uuid;
    /// The 3-letter ISO 4217 currency code (e.g., USD).
    std::string ccyID;
    /// The full currency name (e.g., US Dollar).
    std::string name;
    /// Number of decimal places for standard formatting.
    uint8_t decimalPlaces;
    /// Standard number of days for spot settlement (commonly 2).
    uint8_t settlementDays;
};

ARQ_REG_CATEGORY( RefData, Currency )

template<>
class Traits<Currency>
{
public:
    static constexpr std::string_view const name() { return "Currency"; }

    static constexpr std::array<MemberInfo, 4> membersInfo =
    {
        MemberInfo {
            .name         = "ccyID",
            .comment      = "The 3-letter ISO 4217 currency code (e.g., USD).",
            .physicalType = PhysicalType::String,
            .indexType    = IndexType::Unique,
            .format       = SemanticFormat::String,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "name",
            .comment      = "The full currency name (e.g., US Dollar).",
            .physicalType = PhysicalType::String,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::String,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "decimalPlaces",
            .comment      = "Number of decimal places for standard formatting.",
            .physicalType = PhysicalType::UInt8,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::Integer,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "settlementDays",
            .comment      = "Standard number of days for spot settlement (commonly 2).",
            .physicalType = PhysicalType::UInt8,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::Integer,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        }    
    };
};


// -------------------- User RefData entity --------------------

/// Represents an individual user of the system.
struct User
{
    /// The immutable, globally unique system identifier (Machine Key)
    ID::UUID uuid;
    /// The unique system user ID.
    std::string userID;
    /// The user's full name for display purposes.
    std::string fullName;
    /// The user's contact email address.
    std::string email;
    /// The primary trading desk the user belongs to.
    std::string tradingDesk;
};

ARQ_REG_CATEGORY( RefData, User )

template<>
class Traits<User>
{
public:
    static constexpr std::string_view const name() { return "User"; }

    static constexpr std::array<MemberInfo, 4> membersInfo =
    {
        MemberInfo {
            .name         = "userID",
            .comment      = "The unique system user ID.",
            .physicalType = PhysicalType::String,
            .indexType    = IndexType::Unique,
            .format       = SemanticFormat::String,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "fullName",
            .comment      = "The user's full name for display purposes.",
            .physicalType = PhysicalType::String,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::String,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "email",
            .comment      = "The user's contact email address.",
            .physicalType = PhysicalType::String,
            .indexType    = IndexType::None,
            .format       = SemanticFormat::String,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        },
        MemberInfo {
            .name         = "tradingDesk",
            .comment      = "The primary trading desk the user belongs to.",
            .physicalType = PhysicalType::String,
            .indexType    = IndexType::NonUnique,
            .format       = SemanticFormat::String,
            .uiReadOnly   = false,
            .isPrimaryKey = false
        }    
    };
};


#pragma endregion

#pragma region RefData Helpers

/*
*********************************************
*   Helper typedefs for RefData Entities    *
*********************************************
*/

template<c_RefData... T>
struct EntityList {};

using AllEntities = EntityList<
    Currency,
    User
>;

template<typename... T>
struct EntityRecordList {};

using AllEntityRecords = EntityRecordList<
    Record<Currency>,
    Record<User>
>;

using RecordCollection = TupleVector<
    Record<Currency>,    
    Record<User>    
>;

/*
*********************************************
*   Helper functions for RefData Entities   *
*********************************************
*/

/**
 * @brief Dispatches to the concrete type T based on entity name.
 * @param entityName The name of the RefData entity.
 * @param visitor A callable object with a templated operator()<T>() method.
 * @returns whatever the visitor returns.
 * @throws ARQException if entityName is unknown.
 */
template<typename F>
decltype(auto) dispatch( const std::string_view entityName, F&& visitor )
{
    switch( Str::constexprHash( entityName ) )
    {
        case Str::constexprHash( "Currency" ):
            if (entityName == "Currency") 
                return visitor.template operator()<Currency>();
            break;
        case Str::constexprHash( "User" ):
            if (entityName == "User") 
                return visitor.template operator()<User>();
            break;
    }

    throw ARQException( std::format( "Unknown RefData entity name [{}] - cannot dispatch to function", entityName ) );
}

#pragma endregion

}

#pragma region RefData Type Registration

// Must register outside namespace
ARQ_REG_TYPE( ARQ::RD::Currency );
ARQ_REG_TYPE( ARQ::RD::Record<ARQ::RD::Currency> );
ARQ_REG_TYPE( ARQ::RD::User );
ARQ_REG_TYPE( ARQ::RD::Record<ARQ::RD::User> );

#pragma endregion