// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains the Repository class and its cache for Reference Data entities.

#pragma once
#include <ARQCore/dll.h>

#include <ARQUtils/hashers.h>
#include <ARQCore/refdata_entities.h>
#include <ARQCore/logger.h>
#include <ARQCore/refdata_source.h>

#include <map>
#include <functional>
#include <optional>
#include <mutex>
#include <shared_mutex>

namespace ARQ::RD
{

class Repository;

template<c_RefData T>
class Cache
{
public:
    explicit Cache( const std::map<ID::UUID, T>&& map )
        : m_map( std::move( map ) )
    {}

    [[nodiscard]] std::optional<std::reference_wrapper<const T>> get( const ID::UUID& id ) const
    {
        const auto it = m_map.find( id );
        if( it == m_map.end() )
            return std::nullopt;

        return std::cref( it->second );
    }

private:
    std::map<ID::UUID, T> m_map;

    friend class Repository;
};

class Repository
{
public:
    Repository( const std::string_view dsh )
	    : m_rdSource( RefDataSourceFactory::create( dsh ) )
    {}

    // --- Methods for Currency (CCY) ---

    [[nodiscard]] ARQCore_API bool hasCurrencies() const;

    [[nodiscard]] ARQCore_API std::shared_ptr<Cache<Currency>> Currencies() const;

    ARQCore_API void reloadCurrencies();

    // --- Methods for User (USER) ---

    [[nodiscard]] ARQCore_API bool hasUsers() const;

    [[nodiscard]] ARQCore_API std::shared_ptr<Cache<User>> Users() const;

    ARQCore_API void reloadUsers();

private:
    // --- Methods for Currency (CCY) ---
    void loadInitiallyCurrencies();

    // --- Methods for User (USER) ---
    void loadInitiallyUsers();

private:
    std::shared_ptr<IRefDataSource> m_rdSource;
    mutable std::shared_mutex m_mut;

    std::shared_ptr<Cache<Currency>> m_Currencies;
    std::shared_ptr<Cache<User>> m_Users;
};

}