// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the abstract interface for a Reference Data source.

#pragma once
#include <ARQCore/dll.h>

#include <ARQUtils/core.h>
#include <ARQCore/refdata_entities.h>

#include <vector>
#include <chrono>

namespace ARQ
{

class RefDataSource
{
public:
	virtual ~RefDataSource() = default;

    // --- Methods for Currency (CCY) ---
    [[nodiscard]] ARQCore_API virtual std::vector<RDEntities::Currency> fetchLatestCurrencies() = 0;
    [[nodiscard]] ARQCore_API virtual std::vector<RDEntities::Currency> fetchAsOfCurrencies( const Time::DateTime asof ) = 0;
    ARQCore_API virtual void insertCurrencies( const std::vector<RDEntities::Currency>& data ) = 0;

    // --- Methods for User (USER) ---
    [[nodiscard]] ARQCore_API virtual std::vector<RDEntities::User> fetchLatestUsers() = 0;
    [[nodiscard]] ARQCore_API virtual std::vector<RDEntities::User> fetchAsOfUsers( const Time::DateTime asof ) = 0;
    ARQCore_API virtual void insertUsers( const std::vector<RDEntities::User>& data ) = 0;

};

}