// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the abstract interface for a Reference Data source.

#pragma once
#include <ARQCore/dll.h>

#include <ARQUtils/core.h>
#include <ARQCore/refdata_entities.h>

#include <vector>
#include <chrono>

namespace ARQ::RD
{

class IRefDataSource
{
public:
	virtual ~IRefDataSource() = default;

    // --- Methods for Currency (CCY) ---
    [[nodiscard]] ARQCore_API virtual std::vector<Currency> fetchCurrencies() = 0;
    [[nodiscard]] ARQCore_API virtual std::optional<Currency> fetchCurrency( const ID::UUID uuid ) = 0;
    [[nodiscard]] ARQCore_API virtual std::vector<Currency> fetchAsOfCurrencies( const Time::DateTime asof ) = 0;
    ARQCore_API virtual void upsertCurrencies( const std::vector<Currency>& data ) = 0;

    // --- Methods for User (USER) ---
    [[nodiscard]] ARQCore_API virtual std::vector<User> fetchUsers() = 0;
    [[nodiscard]] ARQCore_API virtual std::optional<User> fetchUser( const ID::UUID uuid ) = 0;
    [[nodiscard]] ARQCore_API virtual std::vector<User> fetchAsOfUsers( const Time::DateTime asof ) = 0;
    ARQCore_API virtual void upsertUsers( const std::vector<User>& data ) = 0;

};

}