// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains the RefDataManager class and its cache for Reference Data entities.

#pragma once
#include <ARQCore/dll.h>

#include <ARQUtils/hashers.h>
#include <ARQCore/refdata_entities.h>
#include <ARQCore/logger.h>
#include <ARQCore/refdata_source.h>

#include <map>
#include <functional>
#include <optional>
#include <mutex>
#include <shared_mutex>

namespace ARQ
{

class RefDataManager;

template<RDEntities::c_RDEntity T>
class RefDataCache
{
public:
    using KeyType = typename RDEntities::Traits<T>::KeyType;

public:
    explicit RefDataCache( const std::map<KeyType, T>&& map )
        : m_map( std::move( map ) )
    {}

    [[nodiscard]] std::optional<std::reference_wrapper<const T>> get( const KeyType& id ) const
    {
        const auto it = m_map.find( id );
        if( it == m_map.end() )
            return std::nullopt;

        return std::cref( it->second );
    }

private:
    std::map<KeyType, T> m_map;

    friend class RefDataManager;
};

class RefDataManager
{
public:

    enum StaleCheck
    {
        NONE = 0,
        USING_CACHE,
        USING_DB
    };

public:
    RefDataManager( const std::string_view dsh )
	    : m_rdSource( RefDataSourceFactory::create( dsh ) )
    {}

    // --- Methods for Currency (CCY) ---

    [[nodiscard]] ARQCore_API bool hasCurrencies() const;

    [[nodiscard]] ARQCore_API std::shared_ptr<RefDataCache<RDEntities::Currency>> Currencies() const;

    ARQCore_API void reloadCurrencies();

    ARQCore_API void insertCurrencies( const std::vector<RDEntities::Currency>& data, const StaleCheck staleCheck = USING_CACHE );
    ARQCore_API void insertCurrency( const RDEntities::Currency& data, const StaleCheck staleCheck = USING_CACHE );

    // --- Methods for User (USER) ---

    [[nodiscard]] ARQCore_API bool hasUsers() const;

    [[nodiscard]] ARQCore_API std::shared_ptr<RefDataCache<RDEntities::User>> Users() const;

    ARQCore_API void reloadUsers();

    ARQCore_API void insertUsers( const std::vector<RDEntities::User>& data, const StaleCheck staleCheck = USING_CACHE );
    ARQCore_API void insertUser( const RDEntities::User& data, const StaleCheck staleCheck = USING_CACHE );

private:
    // --- Methods for Currency (CCY) ---
    void loadInitiallyCurrencies();

    // --- Methods for User (USER) ---
    void loadInitiallyUsers();

private:
    std::shared_ptr<RefDataSource> m_rdSource;
    mutable std::shared_mutex m_mut;

    std::shared_ptr<RefDataCache<RDEntities::Currency>> m_Currencies;
    std::shared_ptr<RefDataCache<RDEntities::User>> m_Users;
};

}