// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for RefData commands.

#pragma once

#include <ARQCore/refdata_entities.h>

namespace ARQ
{
namespace RDCommands
{

// --- Commands for Currency (CCY) ---

struct UpsertCurrencies
{
    struct Item
    {
        ARQ::RDEntities::Currency currency; // TODO: Create Data and Entity structs so only core stuff goes in here
        std::string updatedBy;
        uint32_t expectedVersion = 0;
    }

    std::vector<Item> items;
}

REG_ARQ_TYPE( UpsertCurrencies )

struct DeactivateCurrencies
{
    struct Item
    {
        ARQ::RDEntities::Traits<Currency>::KeyType ccyID;
        std::string updatedBy;
        uint32_t expectedVersion;
    }

    std::vector<Item> items;
}

REG_ARQ_TYPE( DeactivateCurrencies )

// --- Commands for User (USER) ---

struct UpsertUsers
{
    struct Item
    {
        ARQ::RDEntities::User user; // TODO: Create Data and Entity structs so only core stuff goes in here
        std::string updatedBy;
        uint32_t expectedVersion = 0;
    }

    std::vector<Item> items;
}

REG_ARQ_TYPE( UpsertUsers )

struct DeactivateUsers
{
    struct Item
    {
        ARQ::RDEntities::Traits<User>::KeyType userID;
        std::string updatedBy;
        uint32_t expectedVersion;
    }

    std::vector<Item> items;
}

REG_ARQ_TYPE( DeactivateUsers )


}
}