// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Reference Data topics.

#pragma once
#include <ARQCore/dll.h>

#include <ARQCore/refdata_entities.h>

namespace ARQ::RD
{

template<c_RefData T>
struct Topics {};

template<>
struct Topics<Currency>
{
    static constexpr std::string_view commandTopic() { return "ARQ.RefData.Commands.Currency"; }
    static constexpr std::string_view updateTopic()  { return "ARQ.RefData.Updates.Currency"; }
};

template<>
struct Topics<User>
{
    static constexpr std::string_view commandTopic() { return "ARQ.RefData.Commands.User"; }
    static constexpr std::string_view updateTopic()  { return "ARQ.RefData.Updates.User"; }
};

inline std::string_view getCommandTopic( const std::string_view entityName )
{
    return dispatch( entityName, []<typename T>() { return Topics<T>::commandTopic(); } );
}

inline std::string_view getUpdateTopic( const std::string_view entityName )
{
    return dispatch( entityName, []<typename T>() { return Topics<T>::updateTopic(); } );
}

ARQCore_API std::string_view getEntityNameFromCommandTopic( const std::string_view topic );
ARQCore_API std::string_view getEntityNameFromUpdateTopic( const std::string_view topic );

}