// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the interface for a ClickHouse Market Data source.

#pragma once
#include <ARQClickHouse/dll.h>

#include <ARQCore/mktdata_entities.h>
#include <ARQCore/mktdata_source_interface.h>

namespace ARQ
{

class CHMktDataSource : public MktDataSource
{
public:
	CHMktDataSource( const std::string_view dsh )
        : m_dsh( dsh )
    {}

    // --- Methods for FXRate (FXR) ---
    [[nodiscard]] ARQClickHouse_API std::vector<MDEntities::FXRate> fetchFXRates( const std::string_view mktName ) override;
    [[nodiscard]] ARQClickHouse_API std::optional<MDEntities::FXRate> fetchFXRate( const std::string_view mktName, const std::string_view ID ) override;
    ARQClickHouse_API void insertFXRates( const std::vector<MDEntities::FXRate>& data, const std::string_view mktName ) override;

    // --- Methods for EQPrice (EQP) ---
    [[nodiscard]] ARQClickHouse_API std::vector<MDEntities::EQPrice> fetchEQPrices( const std::string_view mktName ) override;
    [[nodiscard]] ARQClickHouse_API std::optional<MDEntities::EQPrice> fetchEQPrice( const std::string_view mktName, const std::string_view ID ) override;
    ARQClickHouse_API void insertEQPrices( const std::vector<MDEntities::EQPrice>& data, const std::string_view mktName ) override;

private:
    std::string m_dsh;
};

}