// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains the interface of the RefData ClickHouse EntitySource classes.

#pragma once
#include <ARQClickHouse/dll.h>

#include <ARQCore/refdata_source.h>

namespace ARQ::CH::RD
{

extern "C" ARQClickHouse_API void registerEntitySources( ARQ::RD::Source& source );

// --- EntitySource class for Currency ---

class CHEntitySource_Currency : public ARQ::RD::IEntitySource<ARQ::RD::Currency>
{
public:
	std::vector<ARQ::RD::Record<ARQ::RD::Currency>> fetch() const override;
	void insert( const std::vector<ARQ::RD::Record<ARQ::RD::Currency>>& data ) override;
};

// --- EntitySource class for User ---

class CHEntitySource_User : public ARQ::RD::IEntitySource<ARQ::RD::User>
{
public:
	std::vector<ARQ::RD::Record<ARQ::RD::User>> fetch() const override;
	void insert( const std::vector<ARQ::RD::Record<ARQ::RD::User>>& data ) override;
};

}