// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines the interface for a ClickHouse Reference Data source.

#pragma once
#include <ARQClickHouse/dll.h>

#include <ARQUtils/time.h>
#include <ARQCore/refdata_entities.h>
#include <ARQCore/refdata_source_interface.h>

namespace ARQ
{

class CHRefDataSource : public RefDataSource
{
public:
    CHRefDataSource( const std::string_view dsh )
        : m_dsh( dsh )
    {}
	virtual ~CHRefDataSource() = default;

    // --- Methods for Currency (CCY) ---
    [[nodiscard]] ARQClickHouse_API std::vector<RDEntities::Currency> fetchCurrencies() override;
    [[nodiscard]] ARQClickHouse_API std::optional<RDEntities::Currency> fetchCurrency( const RDEntities::Traits<RDEntities::Currency>::KeyType& ccyID ) override;
    [[nodiscard]] ARQClickHouse_API std::vector<RDEntities::Currency> fetchAsOfCurrencies( const Time::DateTime asof ) override;
    ARQClickHouse_API void upsertCurrencies( const std::vector<RDEntities::Currency>& data ) override;

    // --- Methods for User (USER) ---
    [[nodiscard]] ARQClickHouse_API std::vector<RDEntities::User> fetchUsers() override;
    [[nodiscard]] ARQClickHouse_API std::optional<RDEntities::User> fetchUser( const RDEntities::Traits<RDEntities::User>::KeyType& userID ) override;
    [[nodiscard]] ARQClickHouse_API std::vector<RDEntities::User> fetchAsOfUsers( const Time::DateTime asof ) override;
    ARQClickHouse_API void upsertUsers( const std::vector<RDEntities::User>& data ) override;

private:
    std::string m_dsh;
};

}