// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines a mock interface for a ClickHouse Market Data source to be used when testing.

#pragma once
#include <gtest/gtest.h>
#include <gmock/gmock.h>

#include <ARQCore/refdata_entities.h>
#include <ARQCore/refdata_source_interface.h>

namespace ARQ
{

class MockMktDataSource : public IMktDataSource
{
public:
	virtual ~MockMktDataSource() = default;

    // --- Mock Methods for FXRate (FXR) ---
    MOCK_METHOD( std::vector<MDEntities::FXRate>, fetchFXRates, ( const std::string_view mktName ), ( override ) );
    MOCK_METHOD( std::optional<MDEntities::FXRate>, fetchFXRate, ( const std::string_view mktName, const std::string_view ID ), ( override ) );
    MOCK_METHOD( void, insertFXRates, ( const std::vector<MDEntities::FXRate>& data, const std::string_view mktName ), ( override ) );

    // --- Mock Methods for EQPrice (EQP) ---
    MOCK_METHOD( std::vector<MDEntities::EQPrice>, fetchEQPrices, ( const std::string_view mktName ), ( override ) );
    MOCK_METHOD( std::optional<MDEntities::EQPrice>, fetchEQPrice, ( const std::string_view mktName, const std::string_view ID ), ( override ) );
    MOCK_METHOD( void, insertEQPrices, ( const std::vector<MDEntities::EQPrice>& data, const std::string_view mktName ), ( override ) );

};

}