//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ARQ.Time {

public partial class Date : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Date(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Date obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Date obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Date() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARQLibPINVOKE.delete_ARQ_Time_Date(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }


    // --- C++ to C# ---
    public global::System.DateOnly? ToDateOnly()
    {
        int ymd = this.getYMD();
        if (ymd == 0)
            return null;
        else
            return new global::System.DateOnly(ymd / 10000, (ymd / 100) % 100, ymd % 100);
    }

    public static implicit operator global::System.DateOnly?(Date d)
    {
        return d?.ToDateOnly();
    }

    // --- C# to C++ ---
    public static implicit operator Date(global::System.DateOnly? d)
    {
        if (!d.HasValue)
            return Date.fromYMD(0);
        else
            return Date.fromYMD(d.Value.Year * 10000 + d.Value.Month * 100 + d.Value.Day);
    }

    public static Date FromDateOnly(global::System.DateOnly? d) => d;

    public override string ToString()
    {
        var d = this.ToDateOnly();
        return d.HasValue ? d.Value.ToString("O") : "null";
    }

  public Date() : this(ARQLibPINVOKE.new_ARQ_Time_Date(), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getYMD() {
    int ret = ARQLibPINVOKE.ARQ_Time_Date_getYMD(swigCPtr);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ARQ.Time.Date fromYMD(int ymd) {
    ARQ.Time.Date ret = new ARQ.Time.Date(ARQLibPINVOKE.ARQ_Time_Date_fromYMD(ymd), true);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
