//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ARQ.Time {

public partial class DateTime : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DateTime(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DateTime obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DateTime obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DateTime() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ARQLibPINVOKE.delete_ARQ_Time_DateTime(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    private const long NULL_SENTINEL = long.MinValue;

    // --- C++ to C# ---
    public global::System.DateTime? ToDateTime()
    {
        long us = this.getUnixMicroseconds();
        if (us == NULL_SENTINEL)
            return null;

        // C# Ticks are 100ns so 1 Microsecond = 10 Ticks
        return global::System.DateTime.UnixEpoch.AddTicks(us * 10);
    }

    public static implicit operator global::System.DateTime?(DateTime dt)
    {
        return dt?.ToDateTime();
    }

    // --- C# to C++ ---
    public static implicit operator DateTime(global::System.DateTime? dt)
    {
        if (!dt.HasValue)
            return DateTime.fromUnixMicroseconds( NULL_SENTINEL );
        
        // Convert to UTC, get Ticks since Epoch, and divide by 10 to get Microseconds
        long ticks = (dt.Value.ToUniversalTime() - global::System.DateTime.UnixEpoch).Ticks;
        return DateTime.fromUnixMicroseconds(ticks / 10);
    }

    public static DateTime FromDateTime(global::System.DateTime? dt) => dt;
    
    public override string ToString()
    {
        var dt = this.ToDateTime();
        return dt.HasValue ? dt.Value.ToString("O") : "null";
    }

  public DateTime() : this(ARQLibPINVOKE.new_ARQ_Time_DateTime(), true) {
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public long getUnixMicroseconds() {
    long ret = ARQLibPINVOKE.ARQ_Time_DateTime_getUnixMicroseconds(swigCPtr);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ARQ.Time.DateTime fromUnixMicroseconds(long us) {
    ARQ.Time.DateTime ret = new ARQ.Time.DateTime(ARQLibPINVOKE.ARQ_Time_DateTime_fromUnixMicroseconds(us), true);
    if (ARQLibPINVOKE.SWIGPendingException.Pending) throw ARQLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
