// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains functions to convert between MktData entity structs and their Protobuf representations.

#pragma once
#include <ARQProtobuf/dll.h>

#include <ARQMarket/mktdata_entities.h>

#include <proto_gen/mktdata_entities.pb.h>

namespace ARQ::Proto::MD
{

// --- Converters for FXRate (FXR) ---

ARQProtobuf_API void toProto( const ARQ::MD::FXRate& arqEntity, FXRate* const protoEntity );
ARQProtobuf_API void toProto(ARQ::MD::FXRate&& arqEntity, FXRate* const protoEntity );

[[nodiscard]] ARQProtobuf_API ARQ::MD::FXRate fromProto( const FXRate& protoEntity );
[[nodiscard]] ARQProtobuf_API ARQ::MD::FXRate fromProto( FXRate&& protoEntity );

// --- Converters for EQPrice (EQP) ---

ARQProtobuf_API void toProto( const ARQ::MD::EQPrice& arqEntity, EQPrice* const protoEntity );
ARQProtobuf_API void toProto(ARQ::MD::EQPrice&& arqEntity, EQPrice* const protoEntity );

[[nodiscard]] ARQProtobuf_API ARQ::MD::EQPrice fromProto( const EQPrice& protoEntity );
[[nodiscard]] ARQProtobuf_API ARQ::MD::EQPrice fromProto( EQPrice&& protoEntity );

}