// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains functions to convert between RefData entity structs and their Protobuf representations.

#pragma once
#include <ARQProtobuf/dll.h>

#include <ARQCore/refdata_entities.h>

#include <proto_gen/refdata_entities.pb.h>

namespace ARQ::Proto::RD
{

// --- Converters for Currency (CCY) ---

ARQProtobuf_API void toProto( const ARQ::RD::Currency& arqEntity, Currency* const protoEntity );
ARQProtobuf_API void toProto(ARQ::RD::Currency&& arqEntity, Currency* const protoEntity );

ARQProtobuf_API [[nodiscard]] ARQ::RD::Currency fromProto( const Currency& protoEntity );
ARQProtobuf_API [[nodiscard]] ARQ::RD::Currency fromProto( Currency&& protoEntity );

// --- Converters for User (USER) ---

ARQProtobuf_API void toProto( const ARQ::RD::User& arqEntity, User* const protoEntity );
ARQProtobuf_API void toProto(ARQ::RD::User&& arqEntity, User* const protoEntity );

ARQProtobuf_API [[nodiscard]] ARQ::RD::User fromProto( const User& protoEntity );
ARQProtobuf_API [[nodiscard]] ARQ::RD::User fromProto( User&& protoEntity );

}