// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Market Data topics.

#pragma once

#include <ARQMarket/mktdata_entities.h>

namespace ARQ::MD
{

template<c_MktData T>
struct Topics {};

template<>
struct Topics<FXRate>
{
    static constexpr std::string_view updateTopic() { return "ARQ.MktData.Updates.FXR"; }
};

template<>
struct Topics<EQPrice>
{
    static constexpr std::string_view updateTopic() { return "ARQ.MktData.Updates.EQP"; }
};

}