// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Market Data entities.

#pragma once

#include <ARQUtils/error.h>
#include <ARQUtils/types.h>
#include <ARQUtils/time.h>
#include <ARQUtils/id.h>
#include <ARQUtils/str.h>
#include <ARQUtils/tuple_vector.h>
#include <ARQUtils/enum.h>
#include <ARQCore/type_registry.h>

#include <string>
#include <cstdint>
#include <string_view>
#include <array>
#include <utility>

namespace ARQ::MD
{

#pragma region Common MktData Types

/*
*********************************************
*    Common types for MktData Entities      *
*********************************************
*/

ARQ_DEFINE_TYPE_CATEGORY( MktData );

// Traits class to get compile-time metadata about a mktdata entity
template<c_MktData T>
class Traits {};

// Records metadata about each member in a MD type
struct MemberInfo
{
    /// Name of the C++ member variable
    std::string_view name;
    /// Documentation string
    std::string_view comment;
    /// The language agnostic type as a string
    std::string_view type;
};

/// Metadata header common to all Market Data records
struct RecordHeader
{
    /// The instrument-specific identifier that, when combined with the Type, forms the globally unique key for this record (e.g., a ticker, ISIN, or curve name)
    std::string       id;
    /// The point-in-time when the market data was effective
    Time::DateTime    asofTs;
    /// Indicates if the record is still active - false means it's been 'tombstoned'
    bool              isActive;
    /// The timestamp of the last update to this record
    Time::DateTime    lastUpdatedTs;
    /// The user who last updated the record
    std::string       lastUpdatedBy;
};

/// The generic storage container for all Market Data entities
template<c_MktData T>
struct Record
{
    using EntityType = T;

    /// Entity metadata
    RecordHeader header;
    /// The actual entity data
    T            data;
};

/// Wraps a record with additional meta data needed when transmitting market data
template<c_MktData T>
struct RecordMessage
{
    using EntityType = T;

    /// Entity Record
    Record<T> record;
    /// The name of the market the record belongs to
    std::string mktName;
};

/// The enumeration of all Market Data entity types
enum class Type
{
    _NOTSET_ = -1,
    FXR,
    EQP,
};

#pragma endregion

#pragma region MktData Entities

/*
***********************************
* Definitions of MktData entities *
***********************************
*/

// -------------------- FXRate MktData entity --------------------

/// Represents a foreign exchange spot rate.
struct FXRate
{
    /// The mid-market rate.
    double mid;
    /// The price at which a market maker is willing to buy.
    double bid;
    /// The price at which a market maker is willing to sell.
    double ask;
};

ARQ_REG_CATEGORY( MktData, FXRate )

template<>
class Traits<FXRate>
{
public:
    static constexpr std::string_view const name()     { return "FXRate"; }
    static constexpr std::string_view const type()     { return "FXR"; }
    static constexpr Type             const typeEnum() { return Type::FXR; }

    static constexpr std::array<MemberInfo, 3> membersInfo =
    {
        MemberInfo {
            .name      = "mid",
            .comment   = "The mid-market rate.",
            .type      = "double"
        },
        MemberInfo {
            .name      = "bid",
            .comment   = "The price at which a market maker is willing to buy.",
            .type      = "double"
        },
        MemberInfo {
            .name      = "ask",
            .comment   = "The price at which a market maker is willing to sell.",
            .type      = "double"
        }    
    };
};


// -------------------- EQPrice MktData entity --------------------

/// Represents pricing information for an equity.
struct EQPrice
{
    /// The price of the last executed trade.
    double last;
    /// The highest price a buyer is willing to pay.
    double bid;
    /// The lowest price a seller is willing to accept.
    double ask;
    /// The opening price for the current trading session.
    double open;
    /// The closing price from the previous trading session.
    double close;
    /// The cumulative volume for the current trading session.
    int64_t volume;
};

ARQ_REG_CATEGORY( MktData, EQPrice )

template<>
class Traits<EQPrice>
{
public:
    static constexpr std::string_view const name()     { return "EQPrice"; }
    static constexpr std::string_view const type()     { return "EQP"; }
    static constexpr Type             const typeEnum() { return Type::EQP; }

    static constexpr std::array<MemberInfo, 6> membersInfo =
    {
        MemberInfo {
            .name      = "last",
            .comment   = "The price of the last executed trade.",
            .type      = "double"
        },
        MemberInfo {
            .name      = "bid",
            .comment   = "The highest price a buyer is willing to pay.",
            .type      = "double"
        },
        MemberInfo {
            .name      = "ask",
            .comment   = "The lowest price a seller is willing to accept.",
            .type      = "double"
        },
        MemberInfo {
            .name      = "open",
            .comment   = "The opening price for the current trading session.",
            .type      = "double"
        },
        MemberInfo {
            .name      = "close",
            .comment   = "The closing price from the previous trading session.",
            .type      = "double"
        },
        MemberInfo {
            .name      = "volume",
            .comment   = "The cumulative volume for the current trading session.",
            .type      = "int64"
        }    
    };
};


#pragma endregion

#pragma region MktData Helpers

/*
*********************************************
*   Helper typedefs for MktData Entities    *
*********************************************
*/

template<c_MktData... T>
struct EntityList {};

using AllEntities = EntityList<
    FXRate,
    EQPrice
>;

template<typename... T>
struct EntityRecordList {};

using AllEntityRecords = EntityRecordList<
    Record<FXRate>,
    Record<EQPrice>
>;

using RecordCollection = TupleVector<
    Record<FXRate>,
    Record<EQPrice>
>;

/*
*********************************************
*   Helper functions for MktData Entities   *
*********************************************
*/

/**
 * @brief Dispatches to the concrete type T based on entity name.
 * @param entityName The name of the MktData entity.
 * @param visitor A callable object with a templated operator()<T>() method.
 * @returns whatever the visitor returns.
 * @throws ARQException if entityName is unknown.
 */
template<typename F>
decltype(auto) dispatch( const std::string_view entityName, F&& visitor )
{
    switch( Str::constexprHash( entityName ) )
    {
        case Str::constexprHash( "FXRate" ):
            if( entityName == "FXRate" ) 
                return visitor.template operator()<FXRate>();
            break;
        case Str::constexprHash( "EQPrice" ):
            if( entityName == "EQPrice" ) 
                return visitor.template operator()<EQPrice>();
            break;
    }

    throw ARQException( std::format( "Unknown MktData entity name [{}] - cannot dispatch to function", entityName ) );
}

/**
 * @brief Dispatches to the concrete type T based on entity type enum.
 * @param entityType The type enum of the MktData entity.
 * @param visitor A callable object with a templated operator()<T>() method.
 * @returns whatever the visitor returns.
 * @throws ARQException if entityType is unknown.
 */
template<typename F>
decltype(auto) dispatch( const Type entityType, F&& visitor )
{
    switch( entityType )
    {
        case Type::FXR:
            return visitor.template operator()<FXRate>();
        case Type::EQP:
            return visitor.template operator()<EQPrice>();
    }

    throw ARQException( std::format( "Unknown MktData entity type [{}] - cannot dispatch to function", Enum::enum_name( entityType ) ) );
}

#pragma endregion

}

#pragma region MktData Type Registration

// Must register outside namespace
ARQ_REG_TYPE( ARQ::MD::FXRate );
ARQ_REG_TYPE( ARQ::MD::Record<ARQ::MD::FXRate> );
ARQ_REG_TYPE( ARQ::MD::RecordMessage<ARQ::MD::FXRate> );
ARQ_REG_TYPE( ARQ::MD::EQPrice );
ARQ_REG_TYPE( ARQ::MD::Record<ARQ::MD::EQPrice> );
ARQ_REG_TYPE( ARQ::MD::RecordMessage<ARQ::MD::EQPrice> );

#pragma endregion