// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Market Data topics.

#pragma once
#include <ARQMarket/dll.h>

#include <ARQMarket/mktdata_entities.h>

namespace ARQ::MD
{

template<c_MktData T>
struct Topics {};

template<>
struct Topics<FXRate>
{
    static constexpr std::string_view observationTopic() { return "ARQ.MktData.Observations.FXR"; }
    static constexpr std::string_view currentTopic()     { return "ARQ.MktData.Current.FXR"; }
};

template<>
struct Topics<EQPrice>
{
    static constexpr std::string_view observationTopic() { return "ARQ.MktData.Observations.EQP"; }
    static constexpr std::string_view currentTopic()     { return "ARQ.MktData.Current.EQP"; }
};

inline std::string_view getObservationTopic( const std::string_view entityName )
{
    return dispatch( entityName, []<typename T>() { return Topics<T>::observationTopic(); } );
}

inline std::string_view getObservationTopic( const Type type )
{
    return dispatch( type, []<typename T>() { return Topics<T>::observationTopic(); } );
}

inline std::string_view getCurrentTopic( const std::string_view entityName )
{
    return dispatch( entityName, []<typename T>() { return Topics<T>::currentTopic(); } );
}

inline std::string_view getCurrentTopic( const Type type )
{
    return dispatch( type, []<typename T>() { return Topics<T>::currentTopic(); } );
}

ARQMarket_API Type getTypeFromObservationTopic( const std::string_view topic );
ARQMarket_API Type getTypeFromCurrentTopic( const std::string_view topic );

}