// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Defines a mock interface for a ClickHouse Reference Data source to be used when testing.

#pragma once
#include <gtest/gtest.h>
#include <gmock/gmock.h>

#include <TMQCore/refdata_entities.h>
#include <TMQCore/refdata_source_interface.h>

namespace TMQ
{

class MockRefDataSource : public RefDataSource
{
public:
	virtual ~MockRefDataSource() = default;

    // --- Mock Methods for Currency (CCY) ---
    MOCK_METHOD( std::vector<RDEntities::Currency>, fetchLatestCurrencies, (), ( override ) );
    MOCK_METHOD( std::vector<RDEntities::Currency>, fetchAsOfCurrencies, ( std::chrono::system_clock::time_point asof ), ( override ) );
    MOCK_METHOD( void, insertCurrencies, ( const std::vector<RDEntities::Currency>& data ), ( override ) );

    // --- Mock Methods for User (USER) ---
    MOCK_METHOD( std::vector<RDEntities::User>, fetchLatestUsers, (), ( override ) );
    MOCK_METHOD( std::vector<RDEntities::User>, fetchAsOfUsers, ( std::chrono::system_clock::time_point asof ), ( override ) );
    MOCK_METHOD( void, insertUsers, ( const std::vector<RDEntities::User>& data ), ( override ) );

};

}