// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains functions to convert between MktData entity structs and their Protobuf representations.

#include <ARQProtobuf/md_entity_proto_converters.h>

namespace ARQ::Proto::MD
{

/*
******************************************************
* Protobuf conversion functions for MktData entities *
******************************************************
*/

// --- Converters for FXRate ---

void toProto( const ARQ::MD::FXRate& arqEntity, FXRate* const protoEntity )
{
    protoEntity->set_mid( arqEntity.mid );
    protoEntity->set_bid( arqEntity.bid );
    protoEntity->set_ask( arqEntity.ask );
}

void toProto( ARQ::MD::FXRate&& arqEntity, FXRate* const protoEntity )
{
    protoEntity->set_mid( std::move( arqEntity.mid ) );
    protoEntity->set_bid( std::move( arqEntity.bid ) );
    protoEntity->set_ask( std::move( arqEntity.ask ) );
}

ARQ::MD::FXRate fromProto( const FXRate& protoEntity )
{
    ARQ::MD::FXRate arqEntity;
    arqEntity.mid = protoEntity.mid();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    return arqEntity;
}

ARQ::MD::FXRate fromProto( FXRate&& protoEntity )
{
    ARQ::MD::FXRate arqEntity;
    arqEntity.mid = protoEntity.mid();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    return arqEntity;
}

// --- Converters for EQPrice ---

void toProto( const ARQ::MD::EQPrice& arqEntity, EQPrice* const protoEntity )
{
    protoEntity->set_last( arqEntity.last );
    protoEntity->set_bid( arqEntity.bid );
    protoEntity->set_ask( arqEntity.ask );
    protoEntity->set_open( arqEntity.open );
    protoEntity->set_close( arqEntity.close );
    protoEntity->set_volume( arqEntity.volume );
    if( arqEntity.vwap )
        protoEntity->set_vwap( *arqEntity.vwap );
}

void toProto( ARQ::MD::EQPrice&& arqEntity, EQPrice* const protoEntity )
{
    protoEntity->set_last( std::move( arqEntity.last ) );
    protoEntity->set_bid( std::move( arqEntity.bid ) );
    protoEntity->set_ask( std::move( arqEntity.ask ) );
    protoEntity->set_open( std::move( arqEntity.open ) );
    protoEntity->set_close( std::move( arqEntity.close ) );
    protoEntity->set_volume( std::move( arqEntity.volume ) );
    if( arqEntity.vwap )
        protoEntity->set_vwap( std::move( *arqEntity.vwap ) );
}

ARQ::MD::EQPrice fromProto( const EQPrice& protoEntity )
{
    ARQ::MD::EQPrice arqEntity;
    arqEntity.last = protoEntity.last();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    arqEntity.open = protoEntity.open();
    arqEntity.close = protoEntity.close();
    arqEntity.volume = protoEntity.volume();
    arqEntity.vwap = protoEntity.has_vwap() ? std::optional<double>( protoEntity.vwap() ) : std::nullopt;
    return arqEntity;
}

ARQ::MD::EQPrice fromProto( EQPrice&& protoEntity )
{
    ARQ::MD::EQPrice arqEntity;
    arqEntity.last = protoEntity.last();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    arqEntity.open = protoEntity.open();
    arqEntity.close = protoEntity.close();
    arqEntity.volume = protoEntity.volume();
    arqEntity.vwap = protoEntity.has_vwap() ? std::optional<double>( protoEntity.vwap() ) : std::nullopt;
    return arqEntity;
}


/*
****************************************************
* Protobuf conversion functions for Misc MD types  *
****************************************************
*/

// --- Converters for RecordHeader ---

void toProto( const ARQ::MD::RecordHeader& arqRecordHeader, RecordHeader* const protoRecordHeader )
{
	protoRecordHeader->set_id( arqRecordHeader.id );
	protoRecordHeader->set_asof_ts( arqRecordHeader.asofTs.microsecondsSinceEpoch() );
	protoRecordHeader->set_is_active( arqRecordHeader.isActive );
	protoRecordHeader->set_last_updated_ts( arqRecordHeader.lastUpdatedTs.microsecondsSinceEpoch() );
	protoRecordHeader->set_last_updated_by( arqRecordHeader.lastUpdatedBy );
}

void toProto( ARQ::MD::RecordHeader&& arqRecordHeader, RecordHeader* const protoRecordHeader )
{
    protoRecordHeader->set_id( std::move( arqRecordHeader.id ) );
	protoRecordHeader->set_asof_ts( arqRecordHeader.asofTs.microsecondsSinceEpoch() );
	protoRecordHeader->set_is_active( arqRecordHeader.isActive );
	protoRecordHeader->set_last_updated_ts( arqRecordHeader.lastUpdatedTs.microsecondsSinceEpoch() );
	protoRecordHeader->set_last_updated_by( std::move( arqRecordHeader.lastUpdatedBy ) );
}

ARQ::MD::RecordHeader fromProto( const RecordHeader& protoRecordHeader )
{
    return {
		.id            = protoRecordHeader.id(),
		.asofTs        = Time::DateTime( Time::Microseconds( protoRecordHeader.asof_ts() ) ),
		.isActive      = protoRecordHeader.is_active(),
		.lastUpdatedTs = Time::DateTime( Time::Microseconds( protoRecordHeader.last_updated_ts() ) ),
		.lastUpdatedBy = protoRecordHeader.last_updated_by()
	};
}

ARQ::MD::RecordHeader fromProto( RecordHeader&& protoRecordHeader )
{
    return {
		.id            = std::move( *protoRecordHeader.mutable_id() ),
		.asofTs        = Time::DateTime( Time::Microseconds( protoRecordHeader.asof_ts() ) ),
		.isActive      = protoRecordHeader.is_active(),
		.lastUpdatedTs = Time::DateTime( Time::Microseconds( protoRecordHeader.last_updated_ts() ) ),
		.lastUpdatedBy = std::move( *protoRecordHeader.mutable_last_updated_by() )
	};
}

// --- Converters for RecordCollection ---

ARQProtobuf_API void toProto( const ARQ::MD::RecordCollection& arqObj, RecordCollection* const protoObj )
{
    arqObj.visitVectors( [&] <ARQ::MD::c_MktData T> ( const std::vector<ARQ::MD::Record<T>>& cppVector )
    {
        if( cppVector.empty() )
            return;

        auto* protoList = ProtoTraits<T>::mutableList( protoObj );
        protoList->Reserve( cppVector.size() );

        for( const auto& cppRecord : cppVector )
        {
            auto* protoRecord = protoList->Add();
            toProto( cppRecord, protoRecord );
        }
    } );
}

ARQProtobuf_API void toProto( ARQ::MD::RecordCollection&& arqObj, RecordCollection* const protoObj )
{
    arqObj.visitVectors( [&] <ARQ::MD::c_MktData T> ( std::vector<ARQ::MD::Record<T>>& cppVector )
    {
        if( cppVector.empty() )
            return;

        auto* protoList = ProtoTraits<T>::mutableList( protoObj );
        protoList->Reserve( cppVector.size() );

        for( auto& cppRecord : cppVector )
        {
            auto* protoRecord = protoList->Add();
            toProto( std::move( cppRecord ), protoRecord ); 
        }
    } );
}

[[nodiscard]] ARQProtobuf_API ARQ::MD::RecordCollection fromProto( const RecordCollection& protoObj )
{
    ARQ::MD::RecordCollection cppObj;

    cppObj.visitVectors( [&] <ARQ::MD::c_MktData T> ( std::vector<ARQ::MD::Record<T>>& cppVector )
    {
        const auto& protoList = ProtoTraits<T>::getList( protoObj );
        if( protoList.empty() )
            return;

        cppVector.reserve( protoList.size() );

        for( const auto& protoRecord : protoList )
            cppVector.push_back( fromProto<T>( protoRecord ) );
    } );

    return cppObj;
}

[[nodiscard]] ARQProtobuf_API ARQ::MD::RecordCollection fromProto( RecordCollection&& protoObj )
{
    ARQ::MD::RecordCollection cppObj;

    cppObj.visitVectors( [&] <ARQ::MD::c_MktData T> ( std::vector<ARQ::MD::Record<T>>& cppVector )
    {
        auto* protoList = ProtoTraits<T>::mutableList( &protoObj );
        if( protoList->empty() )
            return;

        cppVector.reserve( protoList->size() );

        for( auto& protoRecord : *protoList )
            cppVector.push_back( fromProto<T>( std::move( protoRecord ) ) );
    } );

    return cppObj;
}

}