// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains functions to convert between MktData entity structs and their Protobuf representations.

#include <ARQProtobuf/md_entity_proto_converters.h>

namespace ARQ::Proto::MD
{

// --- Converters for FXRate ---

void toProto( const ARQ::MD::FXRate& arqEntity, FXRate* const protoEntity )
{
    protoEntity->set_mid( arqEntity.mid );
    protoEntity->set_bid( arqEntity.bid );
    protoEntity->set_ask( arqEntity.ask );
}

void toProto( ARQ::MD::FXRate&& arqEntity, FXRate* const protoEntity )
{
    protoEntity->set_mid( arqEntity.mid );
    protoEntity->set_bid( arqEntity.bid );
    protoEntity->set_ask( arqEntity.ask );
}

ARQ::MD::FXRate fromProto( const FXRate& protoEntity )
{
    ARQ::MD::FXRate arqEntity;
    arqEntity.mid = protoEntity.mid();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    return arqEntity;
}

ARQ::MD::FXRate fromProto( FXRate&& protoEntity )
{
    ARQ::MD::FXRate arqEntity;
    arqEntity.mid = protoEntity.mid();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    return arqEntity;
}

// --- Converters for EQPrice ---

void toProto( const ARQ::MD::EQPrice& arqEntity, EQPrice* const protoEntity )
{
    protoEntity->set_last( arqEntity.last );
    protoEntity->set_bid( arqEntity.bid );
    protoEntity->set_ask( arqEntity.ask );
    protoEntity->set_open( arqEntity.open );
    protoEntity->set_close( arqEntity.close );
    protoEntity->set_volume( arqEntity.volume );
}

void toProto( ARQ::MD::EQPrice&& arqEntity, EQPrice* const protoEntity )
{
    protoEntity->set_last( arqEntity.last );
    protoEntity->set_bid( arqEntity.bid );
    protoEntity->set_ask( arqEntity.ask );
    protoEntity->set_open( arqEntity.open );
    protoEntity->set_close( arqEntity.close );
    protoEntity->set_volume( arqEntity.volume );
}

ARQ::MD::EQPrice fromProto( const EQPrice& protoEntity )
{
    ARQ::MD::EQPrice arqEntity;
    arqEntity.last = protoEntity.last();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    arqEntity.open = protoEntity.open();
    arqEntity.close = protoEntity.close();
    arqEntity.volume = protoEntity.volume();
    return arqEntity;
}

ARQ::MD::EQPrice fromProto( EQPrice&& protoEntity )
{
    ARQ::MD::EQPrice arqEntity;
    arqEntity.last = protoEntity.last();
    arqEntity.bid = protoEntity.bid();
    arqEntity.ask = protoEntity.ask();
    arqEntity.open = protoEntity.open();
    arqEntity.close = protoEntity.close();
    arqEntity.volume = protoEntity.volume();
    return arqEntity;
}

}