// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains (de)serialisation code for refdata entities and commands

#pragma once
#include <ARQProtobuf/dll.h>

namespace ARQ
{

void registerRefDataSerialisers( Serialiser& serialiser );

// --- Commands for Currency (CCY) ---

class ProtobufTypeSerialiser_UpsertCurrencies : public ISerialisableType<UpsertCurrencies>
{
public:
	ARQProtobuf_API Buffer serialise( const UpsertCurrencies& obj )                      const override;
	ARQProtobuf_API void   deserialise( const BufferView buf, UpsertCurrencies& objOut ) const override;
};

class ProtobufTypeSerialiser_DeactivateCurrencies : public ISerialisableType<DeactivateCurrencies>
{
public:
	ARQProtobuf_API Buffer serialise( const DeactivateCurrencies& obj )                      const override;
	ARQProtobuf_API void   deserialise( const BufferView buf, DeactivateCurrencies& objOut ) const override;
};

// --- Commands for User (USER) ---

class ProtobufTypeSerialiser_UpsertUsers : public ISerialisableType<UpsertUsers>
{
public:
	ARQProtobuf_API Buffer serialise( const UpsertUsers& obj )                      const override;
	ARQProtobuf_API void   deserialise( const BufferView buf, UpsertUsers& objOut ) const override;
};

class ProtobufTypeSerialiser_DeactivateUsers : public ISerialisableType<DeactivateUsers>
{
public:
	ARQProtobuf_API Buffer serialise( const DeactivateUsers& obj )                      const override;
	ARQProtobuf_API void   deserialise( const BufferView buf, DeactivateUsers& objOut ) const override;
};


}