// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains (de)serialisation code for refdata commands

#include "proto_refdata_command_serialisers.h"

#include <ARQUtils/id.h>
#include <ARQProtobuf/rd_entity_proto_converters.h>
#include "helpers.h"

#include <proto_gen/refdata_commands.pb.h>

namespace ARQ::Proto::RD::Cmd
{

void registerRefDataCommandSerialisers( Serialiser& serialiser )
{
    serialiser.registerHandler<ARQ::RD::Cmd::Upsert<ARQ::RD::Currency>>( std::make_unique<ProtobufTypeSerialiser_RDCmdUpsert<ARQ::RD::Currency>>() );
	serialiser.registerHandler<ARQ::RD::Cmd::Deactivate<ARQ::RD::Currency>>( std::make_unique<ProtobufTypeSerialiser_RDCmdDeactivate<ARQ::RD::Currency>>() );
    serialiser.registerHandler<ARQ::RD::Cmd::Upsert<ARQ::RD::User>>( std::make_unique<ProtobufTypeSerialiser_RDCmdUpsert<ARQ::RD::User>>() );
	serialiser.registerHandler<ARQ::RD::Cmd::Deactivate<ARQ::RD::User>>( std::make_unique<ProtobufTypeSerialiser_RDCmdDeactivate<ARQ::RD::User>>() );
}

/*
***************************************************
* Helpers for RefData command proto serialisation *
***************************************************
*/

template<typename ProtoType, typename CmdType>
void setCommonProtoFields( ProtoType& protoObj, const CmdType& cmdObj )
{
	ARQ::Proto::ID::UUID* uuidPtr = protoObj.mutable_target_uuid();
	std::string* uuidBufPtr = uuidPtr->mutable_id();
	*uuidBufPtr = cmdObj.targetUUID.toString();

	std::string* updatedByPtr = protoObj.mutable_updated_by();
	*updatedByPtr = cmdObj.updatedBy;

	protoObj.set_expected_version( cmdObj.expectedVersion );
}

template<typename ProtoType, typename CmdType>
void setCommonCmdFields( ProtoType& protoObj, CmdType& cmdObj )
{
	cmdObj.targetUUID      = ARQ::ID::UUID::fromString( protoObj.target_uuid().id() );
	cmdObj.updatedBy       = std::move( *protoObj.mutable_updated_by() );
	cmdObj.expectedVersion = protoObj.expected_version();
}

/*
************************************************************
* Protobuf TypeSerialiser definitions for refdata commands *
************************************************************
*/

// -------------------- Currency RefData Commands --------------------

template<>
Buffer ProtobufTypeSerialiser_RDCmdUpsert<ARQ::RD::Currency>::serialise( const ARQ::RD::Cmd::Upsert<ARQ::RD::Currency>& obj ) const
{
	Cmd::UpsertCurrency protoObj;
	setCommonProtoFields( protoObj, obj );

	Currency* entityPtr = protoObj.mutable_currency();
	toProto( obj.data, entityPtr );

	return serialiseToBuffer( protoObj );
}

template<>
void ProtobufTypeSerialiser_RDCmdUpsert<ARQ::RD::Currency>::deserialise( const BufferView buf, ARQ::RD::Cmd::Upsert<ARQ::RD::Currency>& objOut ) const
{
	Cmd::UpsertCurrency protoObj;
	if( !protoObj.ParseFromArray( buf.data, buf.size ) )
		throw ARQException( "Cannot deserialise buffer into RefData Cmd UpsertCurrency" );

	setCommonCmdFields( protoObj, objOut );

	objOut.data = fromProto( std::move( *protoObj.mutable_currency() ) );
}

template<>
Buffer ProtobufTypeSerialiser_RDCmdDeactivate<ARQ::RD::Currency>::serialise( const ARQ::RD::Cmd::Deactivate<ARQ::RD::Currency>& obj ) const
{
	Cmd::DeactivateCurrency protoObj;
	setCommonProtoFields( protoObj, obj );

	return serialiseToBuffer( protoObj );
}

template<>
void ProtobufTypeSerialiser_RDCmdDeactivate<ARQ::RD::Currency>::deserialise( const BufferView buf, ARQ::RD::Cmd::Deactivate<ARQ::RD::Currency>& objOut ) const
{
	Cmd::DeactivateCurrency protoObj;
	if( !protoObj.ParseFromArray( buf.data, buf.size ) )
		throw ARQException( "Cannot deserialise buffer into RefData Cmd DeactivateCurrency" );

	setCommonCmdFields( protoObj, objOut );
}

// -------------------- User RefData Commands --------------------

template<>
Buffer ProtobufTypeSerialiser_RDCmdUpsert<ARQ::RD::User>::serialise( const ARQ::RD::Cmd::Upsert<ARQ::RD::User>& obj ) const
{
	Cmd::UpsertUser protoObj;
	setCommonProtoFields( protoObj, obj );

	User* entityPtr = protoObj.mutable_user();
	toProto( obj.data, entityPtr );

	return serialiseToBuffer( protoObj );
}

template<>
void ProtobufTypeSerialiser_RDCmdUpsert<ARQ::RD::User>::deserialise( const BufferView buf, ARQ::RD::Cmd::Upsert<ARQ::RD::User>& objOut ) const
{
	Cmd::UpsertUser protoObj;
	if( !protoObj.ParseFromArray( buf.data, buf.size ) )
		throw ARQException( "Cannot deserialise buffer into RefData Cmd UpsertUser" );

	setCommonCmdFields( protoObj, objOut );

	objOut.data = fromProto( std::move( *protoObj.mutable_user() ) );
}

template<>
Buffer ProtobufTypeSerialiser_RDCmdDeactivate<ARQ::RD::User>::serialise( const ARQ::RD::Cmd::Deactivate<ARQ::RD::User>& obj ) const
{
	Cmd::DeactivateUser protoObj;
	setCommonProtoFields( protoObj, obj );

	return serialiseToBuffer( protoObj );
}

template<>
void ProtobufTypeSerialiser_RDCmdDeactivate<ARQ::RD::User>::deserialise( const BufferView buf, ARQ::RD::Cmd::Deactivate<ARQ::RD::User>& objOut ) const
{
	Cmd::DeactivateUser protoObj;
	if( !protoObj.ParseFromArray( buf.data, buf.size ) )
		throw ARQException( "Cannot deserialise buffer into RefData Cmd DeactivateUser" );

	setCommonCmdFields( protoObj, objOut );
}

}