// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains (de)serialisation code for mktdata entities

#include "proto_mktdata_entity_serialisers.h"

#include <ARQProtobuf/md_entity_proto_converters.h>

#include "helpers.h"

namespace ARQ::Proto::MD
{

void registerMktDataEntitySerialisers( Serialiser& serialiser )
{
    serialiser.registerHandler<ARQ::MD::Record<ARQ::MD::FXRate>>( std::make_unique<ProtobufTypeSerialiser_MDRecord<ARQ::MD::FXRate>>() );
    serialiser.registerHandler<ARQ::MD::RecordMessage<ARQ::MD::FXRate>>( std::make_unique<ProtobufTypeSerialiser_MDRecordMessage<ARQ::MD::FXRate>>() );
    serialiser.registerHandler<ARQ::MD::Record<ARQ::MD::EQPrice>>( std::make_unique<ProtobufTypeSerialiser_MDRecord<ARQ::MD::EQPrice>>() );
    serialiser.registerHandler<ARQ::MD::RecordMessage<ARQ::MD::EQPrice>>( std::make_unique<ProtobufTypeSerialiser_MDRecordMessage<ARQ::MD::EQPrice>>() );
}

/*
************************************************************
* Protobuf TypeSerialiser definitions for mktdata entities *
************************************************************
*/

template<ARQ::MD::c_MktData T>
Buffer ProtobufTypeSerialiser_MDRecord<T>::serialise( const ARQ::MD::Record<T>& obj ) const
{
	typename ProtoTraits<T>::RecordProto protoObj;
	toProto<T>( obj, &protoObj );
	return serialiseToBuffer( protoObj );
}

template<ARQ::MD::c_MktData T>
void ProtobufTypeSerialiser_MDRecord<T>::deserialise( const BufferView buf, ARQ::MD::Record<T>& objOut ) const
{
	typename ProtoTraits<T>::RecordProto protoObj;
	if( !protoObj.ParseFromArray( buf.data, buf.size ) )
		throw ARQException( std::format( "Cannot deserialise buffer into MktData {} Record", ARQ::MD::Traits<T>::name() ) );

	objOut = fromProto<T>( protoObj );
}

template<ARQ::MD::c_MktData T>
Buffer ProtobufTypeSerialiser_MDRecordMessage<T>::serialise( const ARQ::MD::RecordMessage<T>& obj ) const
{
	typename ProtoTraits<T>::RecordMessageProto protoObj;
	toProto<T>( obj, &protoObj );
	return serialiseToBuffer( protoObj );
}

template<ARQ::MD::c_MktData T>
void ProtobufTypeSerialiser_MDRecordMessage<T>::deserialise( const BufferView buf, ARQ::MD::RecordMessage<T>& objOut ) const
{
	typename ProtoTraits<T>::RecordMessageProto protoObj;
	if( !protoObj.ParseFromArray( buf.data, buf.size ) )
		throw ARQException( std::format( "Cannot deserialise buffer into MktData {} RecordMessage", ARQ::MD::Traits<T>::name() ) );

	objOut = fromProto<T>( protoObj );
}

}