// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains functions to convert between RefData entity structs and their Protobuf representations.

#include <ARQProtobuf/rd_entity_proto_converters.h>

namespace ARQ::Proto::RD
{

// --- Converters for Currency ---

void toProto( const ARQ::RD::Currency& arqEntity, Currency* const protoEntity )
{
    std::string* uuidBufPtr = protoEntity->mutable_uuid()->mutable_id();
	*uuidBufPtr = arqEntity.uuid.toString();

    protoEntity->set_ccy_id( arqEntity.ccyID );
    protoEntity->set_name( arqEntity.name );
    protoEntity->set_decimal_places( arqEntity.decimalPlaces );
    protoEntity->set_settlement_days( arqEntity.settlementDays );
}

void toProto( ARQ::RD::Currency&& arqEntity, Currency* const protoEntity )
{
    std::string* uuidBufPtr = protoEntity->mutable_uuid()->mutable_id();
	*uuidBufPtr = arqEntity.uuid.toString();

    protoEntity->set_ccy_id( std::move( arqEntity.ccyID ) );
    protoEntity->set_name( std::move( arqEntity.name ) );
    protoEntity->set_decimal_places( arqEntity.decimalPlaces );
    protoEntity->set_settlement_days( arqEntity.settlementDays );
}

ARQ::RD::Currency fromProto( const Currency& protoEntity )
{
    ARQ::RD::Currency arqEntity;
    arqEntity.uuid = ARQ::ID::UUID::fromString( protoEntity.uuid().id() );
    arqEntity.ccyID = protoEntity.ccy_id();
    arqEntity.name = protoEntity.name();
    arqEntity.decimalPlaces = protoEntity.decimal_places();
    arqEntity.settlementDays = protoEntity.settlement_days();
    return arqEntity;
}

ARQ::RD::Currency fromProto( Currency&& protoEntity )
{
    ARQ::RD::Currency arqEntity;
    arqEntity.uuid = ARQ::ID::UUID::fromString( protoEntity.uuid().id() );
    arqEntity.ccyID = std::move( *protoEntity.mutable_ccy_id() );
    arqEntity.name = std::move( *protoEntity.mutable_name() );
    arqEntity.decimalPlaces = protoEntity.decimal_places();
    arqEntity.settlementDays = protoEntity.settlement_days();
    return arqEntity;
}

// --- Converters for User ---

void toProto( const ARQ::RD::User& arqEntity, User* const protoEntity )
{
    std::string* uuidBufPtr = protoEntity->mutable_uuid()->mutable_id();
	*uuidBufPtr = arqEntity.uuid.toString();

    protoEntity->set_user_id( arqEntity.userID );
    protoEntity->set_full_name( arqEntity.fullName );
    protoEntity->set_email( arqEntity.email );
    protoEntity->set_trading_desk( arqEntity.tradingDesk );
}

void toProto( ARQ::RD::User&& arqEntity, User* const protoEntity )
{
    std::string* uuidBufPtr = protoEntity->mutable_uuid()->mutable_id();
	*uuidBufPtr = arqEntity.uuid.toString();

    protoEntity->set_user_id( std::move( arqEntity.userID ) );
    protoEntity->set_full_name( std::move( arqEntity.fullName ) );
    protoEntity->set_email( std::move( arqEntity.email ) );
    protoEntity->set_trading_desk( std::move( arqEntity.tradingDesk ) );
}

ARQ::RD::User fromProto( const User& protoEntity )
{
    ARQ::RD::User arqEntity;
    arqEntity.uuid = ARQ::ID::UUID::fromString( protoEntity.uuid().id() );
    arqEntity.userID = protoEntity.user_id();
    arqEntity.fullName = protoEntity.full_name();
    arqEntity.email = protoEntity.email();
    arqEntity.tradingDesk = protoEntity.trading_desk();
    return arqEntity;
}

ARQ::RD::User fromProto( User&& protoEntity )
{
    ARQ::RD::User arqEntity;
    arqEntity.uuid = ARQ::ID::UUID::fromString( protoEntity.uuid().id() );
    arqEntity.userID = std::move( *protoEntity.mutable_user_id() );
    arqEntity.fullName = std::move( *protoEntity.mutable_full_name() );
    arqEntity.email = std::move( *protoEntity.mutable_email() );
    arqEntity.tradingDesk = std::move( *protoEntity.mutable_trading_desk() );
    return arqEntity;
}

}