// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains cache classes for Reference Data entities.

namespace ARQ.RD;

public partial class CurrencyCache : ICache 
{
    IRecord ICache.getRecord(ARQ.ID.UUID id) => this.getRecord(id);
    IEnumerable<IRecord> ICache.getList() => this.getList();
}

public partial class UserCache : ICache 
{
    IRecord ICache.getRecord(ARQ.ID.UUID id) => this.getRecord(id);
    IEnumerable<IRecord> ICache.getList() => this.getList();
}
