// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Declares functions for Reference Data serialisation.

#pragma once
#include <TMQSerialisation/dll.h>

#include <TMQUtils/buffer.h>
#include <TMQCore/refdata_entities.h>

#include <fbs_generated/refdata_messages.h>

namespace TMQ
{

// --- Methods for Currency (CCY) ---
[[nodiscard]] TMQSerialisation_API RDEntities::Currency deserialiseCurrency( const fbs::CurrencyPayload& payload );
[[nodiscard]] TMQSerialisation_API Buffer serialiseCurrency( const RDEntities::Currency& entity );

// --- Methods for User (USER) ---
[[nodiscard]] TMQSerialisation_API RDEntities::User deserialiseUser( const fbs::UserPayload& payload );
[[nodiscard]] TMQSerialisation_API Buffer serialiseUser( const RDEntities::User& entity );

}