// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Reference Data entities.

#include <ARQCore/refdata_entities.h>
#include <ARQCore/refdata_meta.h>

namespace ARQ::RD
{

ARQ_REG_RD_ENTITY_META( Currency );
ARQ_REG_RD_ENTITY_META( User );

}