// THIS FILE IS AUTO-GENERATED BY THE CODE-GEN SCRIPT. DO NOT EDIT.
// Contains C++ definitions for Reference Data topics.

#include <ARQCore/refdata_topics.h>

namespace ARQ::RD
{

std::string_view getEntityNameFromCommandTopic( const std::string_view topic )
{
    switch( Str::constexprHash( topic ) )
    {
        case Str::constexprHash( "ARQ.RefData.Commands.Currency" ):
            if( topic == "ARQ.RefData.Commands.Currency" )
                return Traits<Currency>::name();
            break;
        case Str::constexprHash( "ARQ.RefData.Commands.User" ):
            if( topic == "ARQ.RefData.Commands.User" )
                return Traits<User>::name();
            break;
    }

    throw ARQException( std::format( "Unknown RefData command topic [{}] - cannot map to entity name", topic ) );
}

std::string_view getEntityNameFromUpdateTopic( const std::string_view topic )
{
    switch( Str::constexprHash( topic ) )
    {
        case Str::constexprHash( "ARQ.RefData.Updates.Currency" ):
            if( topic == "ARQ.RefData.Updates.Currency" )
                return Traits<Currency>::name();
            break;
        case Str::constexprHash( "ARQ.RefData.Updates.User" ):
            if( topic == "ARQ.RefData.Updates.User" )
                return Traits<User>::name();
            break;
    }

    throw ARQException( std::format( "Unknown RefData update topic [{}] - cannot map to entity name", topic ) );
}

}